{
    'name': 'Food Production',
    'version': '1.0',
    'category': 'Production',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'base_industry_data',
        'hr_homeworking',
        'hr_skills',
        'knowledge',
        'l10n_be_reports',
        'mrp_mps',
        'product_expiry',
        'project_mrp_workorder_account',
        'purchase_mrp',
        'quality_mrp',
        'quality_mrp_workorder_worksheet',
        'sale_mrp',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_purchase_project',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'stock_barcode',
        'survey',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/knowledge_article.xml',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/product_pricelist.xml',
        'data/quality_point.xml',
        'data/mail_message.xml',
        'data/pos_payment_method.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/crm_team.xml',
        'demo/hr_department.xml',
        'demo/account_analytic_plan.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/mrp_workcenter.xml',
        'demo/mrp_routing_workcenter.xml',
        'demo/stock_lot.xml',
        'demo/quality_point.xml',
        'demo/stock_quant.xml',
        'demo/sale_order_template.xml',
        'demo/sale_order_template_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/mrp_production_schedule.xml',
        'demo/mrp_production.xml',
    ],
    'license': 'OPL-1',
    'assets': {
                'web.assets_backend': [
                    'food_production/static/src/js/my_tour.js',
                ],
            },
        'cloc_exclude': [
            'data/knowledge_article.xml',
            'static/src/js/my_tour.js',
        ],
        'images': [
            'images/main.png',
        ],
}