{
    'name': 'Shoe Maker',
    'version': '1.0',
    'category': 'Services',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'industry_fsm_stock',
        'knowledge',
        'pos_sale',
        'purchase',
        'sale_management',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_filter.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_quant.xml',
        'demo/project_task.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'shoe_maker/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
    ],
    'images': ['images/main.png'],
}
