{
    'name': 'Shoemaker',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'industry_fsm_stock',
        'knowledge',
        'pos_sale',
        'purchase',
        'sale_management',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_filter.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_quant.xml',
        'demo/project_task.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=shoe_maker",
    'website': "https://www.odoo.com/industries/shoe-maker",
}
