# -*- coding: utf-8 -*-
{
    'name': 'Commodity Trading',
    'version': '1.0',
    'category': 'industry',
    'description': u"""
Tailored for commodity traders (e.g., soybeans, wheat) with comprehensive functions,
including CRM, quality checks, and broker involvement for product quality and commissions.
""",
    'author': 'odoo',
    'depends': [        
        'account_edi_ubl_cii',
        'account_followup',
        'account_online_synchronization',
        'appointment_crm',
        'base_vat',
        'knowledge',
        'mrp_workorder',
        'partner_autocomplete',
        'product_expiry',
        'product_images',
        'project_sms',
        'quality_control_worksheet',
        'quality_mrp',
        'sale_crm',
        'sale_planning',
        'sale_product_configurator',
        'sale_project',
        'stock_dropshipping',
        'stock_picking_batch',
        'website_appointment',
        'website_crm',
        'website_crm_partner_assign',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/ir_default.xml',
        'data/product_category.xml',
        'data/worksheet_template.xml',
        'data/account_analytic_plan.xml',
        'data/product_template.xml',
        'data/product_pricelist.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_member.xml',
        'data/quality_point.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/res_partner.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/quality_check.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
