# -*- coding: utf-8 -*-
{
    'name': 'Eyewear Shop',
    'version': '1.0',
    'category': 'Industry',
    'description': """
Welcome to Eyewear Shop, your premier destination for stylish and affordable eyewear.
We understand that your eyes are not just a window to your soul but also a canvas for your personal style.
That's why we've curated a stunning collection of eyeglasses and sunglasses that cater to all tastes and preferences.
""",
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'mrp',
        'crm_iap_enrich',
        'delivery_shiprocket',
        'knowledge',
        'sale_management',
        'purchase_stock',
        'website_sale_wishlist',
        'website_appointment',
        'website_sale_comparison',
        'website_sale_loyalty',
        'theme_paptic',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_report.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/product_image.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/stock_lot.xml',
        'demo/res_partner.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/website_view.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/stock_warehouse_orderpoint_replenish.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_ir_attachment.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
