{
    'name': 'Eyewear Shop',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This module is for stylish and affordable eyewear. It will deal with various types of eyewear like Sunglasses, Contact Lenses, Specialty eyewear, etc.
The sales process involves creating sale orders, managing deliveries and invoicing. Additionally, they operate an eCommerce shop for online sales in the eyewear industry.
""",
    'depends': [
        'appointment_crm',
        'knowledge',
        'payment_demo',
        'purchase_stock',
        'point_of_sale',
        'sale_management',
        'web_studio',
        'website_appointment',
        'website_sale_comparison',
        'website_sale_loyalty',
        'website_sale_wishlist',
        'theme_paptic',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_report.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/pos_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/appointment_type.xml',
        'data/payment_provider.xml',
        'data/ir_model_data.xml',
    ],
    'demo': [
        'demo/res_config_settings.xml',
        'demo/website.xml',
        'demo/stock_lot.xml',
        'demo/res_partner.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_rule.xml',
        'demo/loyalty_reward.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/appointment_type.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_template.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/website_ir_attachment.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/pos_confirm.xml',
        'demo/payment_provider.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
