{
    'name': 'Food Trucks',
    'version': '1.1',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'knowledge',
        'planning_field_service_sale_timesheet',
        'pos_restaurant',
        'sale_crm',
    ],
    'data': [
        'data/pos_config.xml',
        'data/crm_tag.xml',
        'data/uom_uom.xml',
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_task.xml',
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'application': True,
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=food_trucks",
    'website': "https://www.odoo.com/all-industries",
}
