{
    'name': 'Bakery Shop',
    'version': '1.0',
    'category': 'Retail',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'hr',
        'knowledge',
        'pos_sale',
        'purchase',
        'stock',
        'website_sale',
        'website_sale_collect',
    ],
    'data': [
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/delivery_carrier.xml',
        'demo/crm_tag.xml',
        'demo/hr_department.xml',
        'demo/hr_job.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/product_product.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo_post.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'bakery/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
