{
    'name': 'Bakery',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'contacts',
        'hr',
        'knowledge',
        'pos_sale',
        'purchase',
        'stock',
        'website_sale_collect',
    ],
    'data': [
        'data/product_product.xml',
        'data/ir_attachment.xml',
        'data/knowledge_article_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/pos_config.xml',
        'data/knowledge_tour.xml',
        'data/hr_department.xml',
        'data/hr_job.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/website_view.xml',
        'demo/delivery_carrier.xml',
        'demo/crm_tag.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/product_product.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_theme_apply.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'bakery/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=bakery",
    'website': "https://www.odoo.com/industries/bakery",
}
