{
    'name': 'Climbing Gym',
    'version': '1.0',
    'category': 'Health and Fitness',
    'depends': [
        'account_invoice_extract',
        'account_online_synchronization',
        'appointment_account_payment',
        'auth_totp_mail',
        'base_industry_data',
        'base_install_request',
        'event_sale',
        'hr_homeworking',
        'hr_skills',
        'partnership',
        'pos_enterprise',
        'pos_epson_printer',
        'pos_event',
        'pos_hr',
        'pos_loyalty',
        'pos_online_payment',
        'pos_sale_subscription',
        'pos_settle_due',
        'product_barcodelookup',
        'project_sale_subscription',
        'project_sms',
        'sale_crm',
        'sale_loyalty',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_project_stock',
        'sign',
        'snailmail_account_followup',
        'survey',
        'web_grid',
        'web_studio',
        'website_appointment',
        'website_crm',
        'website_event',
        'website_knowledge',
        'website_project',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/ir_model_fields.xml',
        'data/res_config_settings.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/planning_slot_template.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_attribute.xml',
        'data/sign_template.xml',
        'data/sign_template_views.xml',
        'data/sign_item.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
    ],
    'demo': [
        'demo/event_tag_category.xml',
        'demo/event_tag.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_slot.xml',
        'demo/crm_team.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_reward.xml',
        'demo/loyalty_rule.xml',
        'demo/product_pricelist_item.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/planning_role.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website_page.xml',
        'demo/sign_request.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
}
