{
    'name': 'Climbing Gym',
    'category': 'Health and Fitness',
    'depends': [
        'base_industry_data',
        'event_sale',
        'knowledge',
        'partnership',
        'pos_event',
        'pos_loyalty',
        'pos_online_payment',
        'pos_sale_subscription',
        'project_sale_subscription',
        'sale_crm',
        'sale_loyalty',
        'sale_planning',
        'sale_project_stock',
        'sign',
        'web_studio',
        'website_crm',
        'website_event',
    ],
    'data': [
        'data/resource_calendar.xml',
        'data/ir_attachment.xml',
        'data/ir_default.xml',
        'data/ir_model_fields.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/res_config_settings.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/product_pricelist_item.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/loyalty_program.xml',
        'data/loyalty_reward.xml',
        'data/loyalty_rule.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/planning_slot_template.xml',
        'data/pos_config.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
    ],
    'demo': [
        'demo/ir_attachment_post.xml',
        'demo/res_config_settings.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_slot.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=climbing_gym",
    'website': "https://www.odoo.com/all-industries",
}
