{
    'name': 'Dropshipping',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'calendar',
        'hr',
        'knowledge',
        'marketing_automation',
        'sale_planning',
        'sale_purchase_project',
        'social_push_notifications',
        'stock_dropshipping',
        'website_sale_mass_mailing',
    ],
    'data': [
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/product_tag.xml',
        'data/stock_picking_type.xml',
        'data/delivery_carrier.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/mailing_mailing.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/payment_provider_demo_post.xml',
        'demo/res_partner.xml',
        'demo/delivery_carrier.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_template.xml',
        'demo/website.xml',
    ],
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=dropshipping",
    'website': "https://www.odoo.com/all-industries",
}
