{
       'name': 'dropshipping',
       'version': '1.0',
       'category': 'Services',
       'depends': [
              'calendar',
              'hr_skills',
              'l10n_be_reports_post_wizard',
              'marketing_automation',
              'sale_planning',
              'sale_purchase_project',
              'social_push_notifications',
              'stock_dropshipping',
              'survey',
              'website_knowledge',
              'website_partner',
              'website_sale_mass_mailing',
       ],
       'data': [
              'data/product_category.xml',
              'data/product_template.xml',
              'data/product_attribute.xml',
              'data/product_attribute_value.xml',
              'data/product_template_attribute_line.xml',
              'data/product_template_attribute_value.xml',
              'data/product_product.xml',
              'data/product_tag.xml',
              'data/res_partner.xml',
              'data/stock_picking_type.xml',
              'data/purchase_order.xml',
              'data/delivery_carrier.xml',
              'data/knowledge_article.xml',
              'data/knowledge_article_favorite.xml',
              'data/mail_message.xml',
              'data/knowledge_tour.xml',
              'data/res_config_settings.xml',
              'data/mailing_mailing.xml'
       ],
       'demo': [
              'demo/website.xml',
              'demo/website_view.xml',
              'demo/website_theme_apply.xml',
              'demo/res_partner_category.xml',
              'demo/hr_department.xml',
              'demo/hr_employee.xml',
              'demo/product_supplierinfo.xml',
              'demo/sale_order.xml',
              'demo/sale_order_line.xml',
              'demo/purchase_order.xml',
              'demo/purchase_order_line.xml',
              'demo/purchase_order_post.xml',
              'demo/stock_quant.xml',
              'demo/website_page.xml',
              'demo/website_menu.xml',
              'demo/ir_attachment_post.xml',
              'demo/sale_order_confirm.xml',
              'demo/product_template.xml',
              'demo/payment_provider_demo_post.xml'
              ],
       'assets': {
              'web.assets_backend': [
                     'dropshipping/static/src/js/my_tour.js',
              ]
       },
       'author': 'Odoo S.A.',
       "cloc_exclude": [
              "data/knowledge_article.xml",
              "static/src/js/my_tour.js",
              "demo/website_view.xml",
       ],
       'images': ['images/main.png'],
       'license': 'OPL-1'
}
