{
    'name': 'Vineyard',
    'version': '1.0',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'appointment_google_calendar',
        'appointment_hr',
        'base_industry_data',
        'excise_management',
        'hr_sign',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'mrp_plm',
        'pos_enterprise',
        'product_expiry',
        'project_purchase',
        'quality_mrp',
        'sale_planning',
        'web_studio',
        'website_appointment_sale_project',
    ],
    'data': [
        'data/res_config_setting.xml',
        'data/stock_warehouse.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/knowledge_article.xml',
        'data/stock_location.xml',
        'data/stock_picking_type.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/uom_uom.xml',
        'data/worksheet_template.xml',
        'data/project_project.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        # 'data/product_attribute.xml',
        'data/mrp_bom.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_menu.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/appointment_type.xml',
        'demo/crm_tag.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_lead.xml',
        'demo/project_project.xml',
        'demo/purchase_order_line.xml',
        'demo/stock_lot.xml',
        'demo/mrp_production.xml',
        'demo/mrp_bom_line.xml',
        'demo/mrp_eco.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/stock_quant.xml',
        'demo/quality_point.xml',
        'demo/quality_check.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website_theme_apply.xml',
        'demo/website_view.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/ir_actions_server.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
