{
    'name': 'Vineyard',
    'version': '1.0',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'appointment_google_calendar',
        'appointment_hr',
        'base_industry_data',
        # 'crm_enterprise',
        # 'hr_homeworking',
        'hr_sign',
        # 'hr_skills',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        # 'l10n_be_reports',
        'mrp_plm',
        'pos_enterprise',
        # 'pos_hr',
        # 'pos_online_payment',
        'product_expiry',
        # 'project_mrp_workorder_account',
        'project_purchase',
        # 'purchase_mrp',
        'quality_mrp',
        # 'quality_mrp_workorder',
        # 'sale_crm',
        # 'sale_mrp',
        'sale_planning',
        # 'sale_purchase_stock',
        # 'stock_barcode',
        # 'survey',
        'website_appointment_sale_project',
        # 'website_crm',
        # 'website_sale_stock',
        'web_studio',
    ],
    'data': [
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        # 'data/crm_stage.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/uom_uom.xml',
        'data/project_task_type.xml',
        'data/worksheet_template.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_attribute.xml',
        'data/quality_point.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/appointment_type.xml',
        'demo/crm_tag.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/account_analytic_account.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/project_project.xml',
        'demo/pos_session.xml',
        'demo/purchase_order_line.xml',
        'demo/mrp_bom.xml',
        'demo/stock_lot.xml',
        'demo/mrp_production.xml',
        'demo/mrp_bom_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/quality_check.xml',
        'demo/website_theme_apply.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/ir_action_server.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
