{
    'name': 'Vineyard',
    'version': '1.0',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'crm',
        'base_industry_data',
        'excise_management',
        'industry_fsm_sale_report',
        'knowledge',
        'mrp_plm',
        'pos_enterprise',
        'product_expiry',
        'purchase',
        'quality_mrp',
        'website_appointment_sale_project',
    ],
    'data': [
        'data/res_config_setting.xml',
        'data/stock_warehouse.xml',
        'data/ir_model.xml',
        'data/ir_sequence.xml',
        'data/ir_model_fields.xml',
        'data/stock_location.xml',
        'data/stock_picking_type.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/uom_uom.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/product_tag.xml',
        'data/pos_config.xml',
        'data/mrp_bom_byproduct.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/base_automation.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/appointment_type.xml',
        'demo/crm_tag.xml',
        'demo/res_partner.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/crm_lead.xml',
        'demo/stock_picking.xml',
        'demo/stock_move.xml',
        'demo/mrp_production.xml',
        'demo/mrp_eco_stage.xml',
        'demo/mrp_eco.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_tags.xml',
        'demo/project_task.xml',
        'demo/project_task_recurrence.xml',
        'demo/project_task_post.xml',
        'demo/quality_point.xml',
        'demo/quality_check.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/stock_picking_post.xml',
        'demo/spreadsheet_dashboard.xml',
        'demo/payment_provider_demo.xml',
        'demo/website_theme_apply.xml',
        'demo/website_view.xml',
        'demo/website.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/ir_actions_server.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'license': 'OPL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=vineyard",
    'website': "https://www.odoo.com/industries/vineyard",
}
