{
    'name': 'Outdoor Activities',
    'version': '1.0',
    'category': 'Health and Fitness',
    'depends': [
        'appointment_account_payment',
        'crm_enterprise',
        'event_crm',
        'knowledge',
        'pos_sale',
        'sale_service',
        'website_crm',
        'website_event_sale',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/crm_stages.xml',
        'data/crm_tags.xml',
        'data/product_product.xml',
        'data/event_event.xml',
        'data/appointment_resource.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favourite.xml',
        'data/knowledge_tour.xml',
        'data/pos_config.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
        'demo/website_views.xml',
        'demo/crm_lead.xml',
        'demo/mail_message.xml',
        'demo/event_event.xml',
        'demo/calender_event.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/payment_provider_demo_post.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'outdoor_activities/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_views.xml',
        'static/src/js/my_tour.js',
    ],
    'images': ['images/main.png'],
}
