{
    'name': 'Outdoor Activities',
    'version': '1.2',
    'category': 'Health and Fitness',
    'depends': [
        'appointment_account_payment',
        'crm_enterprise',
        'event_crm',
        'knowledge',
        'pos_sale',
        'pos_stock',
        'sale_service',
        'website_appointment',
        'website_crm',
        'website_event_sale',
        'website_sale',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/crm_stages.xml',
        'data/crm_tags.xml',
        'data/product_product.xml',
        'data/appointment_resource.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favourite.xml',
        'data/knowledge_tour.xml',
        'data/pos_config.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        # website.xml creates the website record everything below references; the
        # server action must run right after it and before any page, so that it
        # deactivates the generic views instead of our custom pages.
        'demo/website/website.xml',
        'demo/website/server_actions.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/thanks_contact_us.xml',
        'demo/crm_lead.xml',
        'demo/mail_message.xml',
        'demo/event_event.xml',
        'demo/calender_event.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/ir_attachment_post.xml',
        'demo/payment_provider_demo_post.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'outdoor_activities/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/thanks_contact_us.xml',
        'static/src/scss/primary_variables.scss',
        'static/src/js/my_tour.js',
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=outdoor_activities",
    'website': "https://www.odoo.com/all-industries",
}
