{
<<<<<<< 44142a93dfc6489c665550932c07f6317434cdf6
    'name': 'Construction Builder',
    'version': '1.3',
    'category': 'Construction',
||||||| e5a1ba433a012ad0dcff740c631f8f97783d2861
    'name': 'Construction',
    'version': '1.0',
    'category': 'Construction',
    'description': """
This industry is ideal for construction businesses proficient in managing projects from conception to completion,
focusing on accurate quoting, efficient planning, seamless execution, and excellent customer service, ...
""",
=======
    'name': 'Construction',
    'version': '1.0',
    'category': 'Real Estate, Construction and Maintenance',
    'description': """
This industry is ideal for construction businesses proficient in managing projects from conception to completion,
focusing on accurate quoting, efficient planning, seamless execution, and excellent customer service, ...
""",
>>>>>>> 20014fd4a7f3eef3b4149c7cb00d24f3495f074a
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'documents',
        'helpdesk',
        'knowledge',
        'planning_field_service_sale_stock',
        'purchase_stock',
        'sale_crm',
        'sale_margin',
        'sale_project_forecast',
    ],
    'data': [
        'data/documents_folder.xml',
        'data/res_config_settings.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/ir_ui_view.xml',
        'data/project_project.xml',
        'data/ir_attachment_pre.xml',
        'data/uom_uom.xml',
        'data/planning_role.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/mail_activity_type.xml',
        'data/hr_job.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/documents_folder.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/resource_resource.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_quant.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/project_tags.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_project.xml',
        'demo/project_task_post.xml',
        'demo/project_tags_post.xml',
        'demo/documents_document.xml',
        'demo/mail_activity.xml',
        'demo/account_analytic_line.xml',
        'demo/project_update.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot.xml',
        'demo/sale_order_spreadsheet.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=construction",
    'website': "https://www.odoo.com/industries/construction",
}
