{
    'name': '3PL Logistic Company',
    'author': 'Odoo S.A.',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'crm_sale_subscription',
        'documents_hr',
        'logistic_company',
        'quality_mrp',
        'sale_service',
        'web_studio',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/x_fee_rate.xml',
        'data/ir_model_fields.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/product_pricelist_item.xml',
        'data/stock_package_type.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/stock_storage_category.xml',
        'data/stock_location.xml',
        'data/ir_ui_view.xml',
        'data/qweb_view.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
        'data/stock_warehouse.xml',
        'data/res_config_settings.xml',
        'data/spreadsheet_dashboard.xml',
        'data/mail_message.xml',
        'data/website.xml',
    ],
    'demo': [
        'demo/quality_point.xml',
        'demo/res_partner.xml',
        'demo/product_template.xml',
        'demo/mrp_bom.xml',
        'demo/mrp_bom_line.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/x_stock_history.xml',
        'demo/website_theme_apply.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_quant_package.xml',
        'demo/account_move.xml',
        'demo/stock_picking.xml',
        'demo/stock_move.xml',
        'demo/quality_check.xml',
        'demo/stock_move_line.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/qweb_view.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
