{
    'name': '3PL Logistic Company',
    'author': 'Odoo S.A.',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'crm_sale_subscription',
        'documents_hr',
        'knowledge',
        'product_expiry',
        'purchase',
        'quality_control',
        'quality_mrp',
        'sale_management',
        'sale_service',
        'sale_subscription',
        'stock',
        'web_studio',
        'website',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/portal_templates.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/x_fee_rate.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/product_pricelist_item.xml',
        'data/stock_package_type.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/stock_storage_category.xml',
        'data/stock_location.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/ir_cron.xml',
        'data/stock_warehouse.xml',
        'data/res_config_settings.xml',
        'data/spreadsheet_dashboard.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/quality_point.xml',
        'demo/stock_location.xml',
        'demo/res_partner.xml',
        'demo/product_template.xml',
        'demo/qweb_view.xml',
        'demo/mrp_bom.xml',
        'demo/mrp_bom_line.xml',
        'demo/stock_lot.xml',
        'demo/website_theme_apply.xml',
        'demo/crm_lead.xml',
        'demo/stock_package.xml',
        'demo/x_stock_history.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_picking.xml',
        'demo/stock_move.xml',
        'demo/stock_move_line.xml',
        'demo/website.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/portal_templates.xml',
        'demo/qweb_view.xml',
    ],
    'license': 'OEEL-1',
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=3pl_logistic_company",
    'website': "https://www.odoo.com/all-industries",
}
