{
    'name': 'Carpenter',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'documents_hr',
        'knowledge',
        'project_purchase',
        'sale_mrp',
        'sale_timesheet',
        'stock_dropshipping',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_ui_menu.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/stock_lot.xml',
        'demo/mrp_production.xml',
        'demo/ir_attachment_post.xml',
        'demo/stock_move.xml',
        'demo/stock_quant.xml',
        'demo/hr_employee.xml',
        'demo/mrp_production_post.xml',
        'demo/documents_document.xml',
        'demo/account_analytic_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_spreadsheet.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=carpenter",
    'website': "https://www.odoo.com/all-industries",
}
