{
    'name': 'Carpenter',
    'version': '1.0',
    'category': 'Retail',
    'description': """
""",
    'depends': [
        'base_automation',
        'contacts',
        'knowledge',
        'project',
        'purchase',
        'sale_management',
        'sale_timesheet',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/report_view.xml',
        'data/ir_actions_report.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/base_automation.xml',
        'data/ir_attachment_pre.xml',
        'data/project_task_type.xml',
        'data/project_tags.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_user.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'carpenter/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/ir_ui_view.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
