{
    'name': 'Carpenter',
    'version': '1.0',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'base_industry_data',
        'crm_enterprise',
        'documents_account',
        'documents_hr',
        'documents_product',
        'documents_project',
        'documents_sign',
        'documents_spreadsheet',
        'hr_homeworking',
        'hr_sign',
        'hr_skills',
        'knowledge',
        'l10n_be_reports',
        'project_mrp_workorder_account',
        'project_purchase',
        'sale_crm',
        'sale_mrp',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_timesheet_enterprise',
        'spreadsheet_sale_management',
        'stock_barcode',
        'stock_dropshipping',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/documents_document.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/stock_picking_type.xml',
        'data/mail_message.xml',
        'data/crm_lead.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        # 'demo/account_analytic_account.xml',
        # 'demo/crm_lead.xml',
        'demo/sale_order.xml',
        # 'demo/project_project.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        # 'demo/stock_lot.xml',
        # 'demo/mrp_production.xml',
        'demo/sale_order_line.xml',
        # 'demo/project_task.xml',
        # 'demo/stock_quant.xml',
        # 'demo/hr_employee.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_analytic_line.xml',
        'demo/purchase_order_post.xml',
        # 'demo/product_supplierinfo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
