{
    'name': 'Food Distribution',
    'version': '1.0',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'base_industry_data',
        'knowledge',
        'mrp_mps',
        'product_expiry',
        'project_mrp_workorder_account',
        'purchase_mrp',
        'quality_mrp_workorder_worksheet',
        'sale_mrp',
        'sale_planning',
        'sale_purchase_project',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'stock_barcode',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/res_company.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/mrp_bom_post.xml',
        'data/mrp_workcenter.xml',
        'data/mrp_routing_workcenter.xml',
        'data/quality_point.xml',
        'data/mail_message.xml',
        'data/pos_payment_method.xml',
        'data/knowledge_article_favorite.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/stock_warehouse_orderpoint.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/mrp_production_schedule.xml',
        'demo/mrp_production.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=food_distribution",
}
