{
    'name': 'Fitness Center',
    'version': '1.4',
    'category': 'Health and Fitness',
    'depends': [
        'base_industry_data',
        'calendar',
        'contacts',
        'hr',
        'maintenance',
        'partnership',
        'planning',
        'pos_sale',
        'pos_stock',
        'purchase',
        'sale_project',
        'sale_subscription',
        'website_appointment',
        'website_event',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/pos_category.xml',
        'data/product_pricelist.xml',
        'data/sale_subscription.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/appointment_resource.xml',
        'data/appointment_type.xml',
        'data/appointment_slot.xml',
        'data/maintenance_equipment.xml',
        'data/appointment_view.xml',
        'data/planning_role.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/maintenance_request.xml',
        'demo/product_template.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot.xml',
        'demo/website/website.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/views/website_sale_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/courses.xml',
        'demo/website/pages/about_us.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/events.xml',
        'demo/website/server_actions.xml',
        'demo/event_event.xml',
        'demo/product_pricelist.xml',
        'demo/payment_provider_demo_post.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'fitness/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/appointment_view.xml",
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "demo/website/views/website_templates.xml",
        "demo/website/views/website_sale_templates.xml",
        "demo/website/pages/home.xml",
        "demo/website/pages/courses.xml",
        "demo/website/pages/about_us.xml",
        "demo/website/pages/contactus.xml",
        "demo/website/pages/events.xml",
        "static/src/scss/primary_variables.scss",
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=fitness",
    'website': "https://www.odoo.com/industries/fitness-center",
}
