{
    'name': 'Night Clubs',
    'version': '1.0',
    'category': 'Hospitaility',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'event_product',
        'event_sale',
        'knowledge',
        'pos_restaurant',
        'purchase',
        'sale',
        'social',
        'website_event',
        'website_sale',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/pos_config.xml',
        'data/product_product.xml',
        'data/event_type.xml',
        'data/event_type_ticket.xml',
        'data/event_event.xml',
        'data/event_slot.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_public_category.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_menu.xml',
    ],
    'demo': [
        'demo/event_event.xml',
        'demo/event_tag_category.xml',
        'demo/event_tag.xml',
        'demo/res_partner.xml',
        'demo/sale_order.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=night_clubs",
    'website': "https://www.odoo.com/all-industries",
}
