{
    'name': 'Gardening',
    'version': '1.0',
    'category': 'Construction',
    'depends': [
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'sale_crm',
        'sale_purchase_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/quotation_template.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_user.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/timesheet.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'gardening/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
