{
    'name': 'Law Firm',
    'version': '2.0',
    'category': 'Services',
    'depends': [
        'contacts',
        'crm',
        'documents_project',
        'hr_expense',
        'hr_timesheet',
        'knowledge',
        'mail',
        'project_enterprise',
        'sale_management',
        'sale_timesheet_enterprise',
        'sign',
        'web_studio',
        'website',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/res_groups.xml',
        'data/ir_default.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/ir_filters.xml',
        'data/documents_folder.xml',
        'data/project_task_type.xml',
        'data/project_tags.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/crm_stage.xml',
        'data/crm_tag.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/hr_employee_category.xml',
        'data/sign_item_role.xml',
        'data/ir_attachment.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/hr_job.xml',
        'demo/hr_employee.xml',
        'demo/sign_template.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/sale_order_spreadsheet.xml',
        'demo/knowledge_article.xml',
        'demo/knowledge_article_favorite.xml',
        'demo/documents_document.xml',
        'demo/hr_expense.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'industry_lawyer/static/src/js/my_tour.js',
            'industry_lawyer/static/src/js/mail_composer.js',
            'industry_lawyer/static/src/js/reload.js',
            'industry_lawyer/static/src/js/submit_for_approval.js',
            'industry_lawyer/static/src/js/suggested_recipients.js',
            'industry_lawyer/static/src/xml/composer.xml',
            'industry_lawyer/static/src/js/approval_state_selection.js',
            'industry_lawyer/static/src/xml/approval_state_selection.xml',
            'industry_lawyer/static/src/scss/approval_state_selection.scss',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'static/src/js/mail_composer.js',
        'static/src/js/reload.js',
        'static/src/js/submit_for_approval.js',
        'static/src/js/suggested_recipients.js',
        'static/src/xml/composer.xml',
        'static/src/js/approval_state_selection.js',
        'static/src/xml/approval_state_selection.xml',
        'static/src/scss/approval_state_selection.scss',
        'data/website_view.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=industry_lawyer",
    'website': "https://www.odoo.com/industries/law-firm",
}
