{
    'name': 'Law Firm',
    'version': '1.1',
    'category': 'Services',
    'description': """
This module installs a configuration that presets the modules and configure Odoo for a law firm.
""",
    'depends': [
        'contacts',
        'crm',
        'documents_project',
        'hr_timesheet',
        'knowledge',
        'project_enterprise',
        'sale_management',
        'sale_timesheet_enterprise',
        'sign',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/project_task_type.xml',
        'data/project_tags.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/crm_stage.xml',
        'data/crm_tag.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/hr_employee_category.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/hr_job.xml',
        'demo/hr_employee.xml',
        'demo/sign_template.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/documents_document.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'industry_lawyer/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
