{
    'name': 'Eyewear Shop',
    'version': '1.0',
    'category': 'Health and Fitness',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'account_online_synchronization',
        'appointment_crm',
        'crm_enterprise',
        'hr_skills',
        'point_of_sale',
        'pos_online_payment',
        'product_barcodelookup',
        'sale_purchase_stock',
        'theme_clean',
        'web_studio',
        'website_appointment',
        'website_crm',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/appointment_resource.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/x_res_partner_line_0ace2.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/website_theme_apply.xml',
        'demo/ir_ui_view.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/hr_department.xml',
        'demo/pos_session.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/appointment_resource.xml',
        'demo/x_res_partner_line_0ace2.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'eyewear/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
