{
    'name': 'Veterinary Clinic',
    'version': '1.0',
    'category': 'Health and Fitness',
    'author': 'Odoo S.A.',
    'depends': [
        'crm_enterprise',
        'documents_sign',
        'industry_fsm_sale_report',
        'knowledge',
        'pos_online_payment',
        'sale_crm',
        'sale_planning',
        'web_studio',
        'website_appointment_crm',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/ir_sequence.xml',
        'data/crm_stage.xml',
        'data/documents_document.xml',
        'data/knowledge_article.xml',
        'data/ir_attachment_post.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/x_species.xml',
        'data/x_illnesses.xml',
        'data/x_species_line.xml',
        'data/x_pets.xml',
        'data/x_vaccines.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/appointment_type.xml',
        'data/appointment_question.xml',
        'data/appointment_answer.xml',
        'data/crm_tag.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/appointment_type.xml',
        'demo/appointment_question.xml',
        'demo/crm_team.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/crm_lead.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/x_pets.xml',
        'demo/website_theme_apply.xml',
        'demo/stock_warehouse_orderpoint.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'veterinary_clinic/static/src/js/my_tour.js',
        ]
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
