{
    'name': 'Property Owner Association',
    'version': '1.3',
    'category': 'Services',
    'depends': [
        'account_check_printing',
        'account_followup',
        'account_peppol',
        'accountant',
        'appointment_account_payment',
        'calendar',
        'contacts',
        'documents_product',
        'documents_project_sale',
        'documents_spreadsheet',
        'helpdesk_sale_timesheet',
        'hr',
        'knowledge',
        'l10n_be_reports_post_wizard',#need to remove
        'sale_subscription',
        'web_studio',
],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/account_analytic_plan.xml',
        'data/ir_filters.xml',
        'data/ir_default.xml',
        # 'data/meter_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_act_window_view.xml',
        'data/ir_ui_view.xml',
        'data/qweb_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/project_task_type.xml',
        'data/documents_folder.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_subscription_plan.xml',
        'data/sale_subscription_pricing.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/x_buildings_tag.xml',
        'data/knowledge_tour.xml',
        'data/res_partner.xml',
        'data/res_company.xml',
        'data/x_meters.xml',
        'data/x_distribution_key.xml',
        'data/x_vote_criteria.xml',
        'data/x_calendar_event_line_a1bce.xml',
        'data/x_meeting.xml',
        'data/x_properties_types.xml',
        'data/x_properties_tag.xml',
        'data/x_buildings.xml',
        'data/x_property.xml',
        'data/x_property_line_019a4.xml',
        'data/account_analytic_account.xml',
        'data/x_meter_reading.xml',
        'data/x_period.xml',
        'data/x_property_line_07bf7.xml',
        'data/x_property_line_bfb14.xml',
        'data/x_ratios.xml'
    ],
    'demo': [
        'demo/x_calendar_event_line_a1bce_line_a3f04.xml',
        'demo/calendar_event.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        # 'demo/sale_order_post.xml',
        'demo/helpdesk_team.xml',
        'demo/helpdesk_ticket.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'condominium/static/src/js/acquisition.js',
            'condominium/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        'data/qweb_view.xml',
        "data/knowledge_article.xml",
        "static/src/js/acquisition.js",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=condominium",
    'website': "https://www.odoo.com/industries/property-owner-association",
}
