{
    'name': 'Property Owner Association',
    'version': '2.0',
    'category': 'Services',
    'depends': [
        'account_check_printing',
        'accountant',
        'appointment',
        'contacts',
        'documents_project_sale',
        'helpdesk',
        'hr_timesheet',
        'knowledge',
        'sale_subscription',
        'sign',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/report_paperformat.xml',
        'data/ir_actions_report.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/account_analytic_plan.xml',
        'data/ir_filters.xml',
        'data/meter_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/qweb_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/ir_rule.xml',
        'data/project_task_type.xml',
        'data/documents_folder.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_subscription_plan.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/x_buildings_tag.xml',
        'data/knowledge_tour.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/x_meters.xml',
        'data/x_vote_criteria.xml',
        'data/x_properties_types.xml',
        'data/x_properties_tag.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/res_partner.xml',
        'demo/res_company.xml',
        'demo/x_buildings.xml',
        'demo/x_property.xml',
        'demo/x_property_line_owner.xml',
        'demo/x_meter_reading.xml',
        'demo/x_distribution_key.xml',
        'demo/account_move.xml',
        'demo/account_move_line.xml',
        'demo/x_calendar_event_line.xml',
        'demo/calendar_event.xml',
        'demo/calendar_attendee.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_move_confirm.xml',
        'demo/helpdesk_team.xml',
        'demo/helpdesk_ticket.xml',
        'demo/x_calendar_event_line_motion.xml',
        'demo/x_calendar_event_line_motion_line_vote.xml',
        'demo/x_ratios.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'condominium/static/src/js/acquisition.js',
            'condominium/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        'data/qweb_view.xml',
        "data/knowledge_article.xml",
        "static/src/js/acquisition.js",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=condominium",
    'website': "https://www.odoo.com/industries/property-owner-association",
}
