{
    'name': 'Construction Work Items',
    'version': '1.0',
    'category': 'Construction',
    'author': 'Odoo S.A.',
    'depends': [
        'sale_management',
        'construction',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/ir_default.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/x_bill_of_materials.xml',
        'data/x_bill_of_materials_line.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/account_analytic_account.xml',
        'demo/project_project.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/x_bill_of_materials.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [],
    'website': "https://www.odoo.com/all-industries",
}
