{
    'name': 'Construction Work Items',
    'version': '1.0',
    'category': 'Hidden/Tools',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'construction',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/ir_default.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/x_work_item.xml',
        'data/x_work_item_line.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/ir_attachment.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/project_project.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
    ],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=construction",
    'website': "https://www.odoo.com/industries/construction",
}
