{
    'name': 'Wedding Planner',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'hr_calendar',
        'knowledge',
        'project_enterprise',
        'purchase_requisition',
        'sale_crm',
        'sale_management',
        'sale_project',
        'sign',
        'social',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/ir_attachment_post.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/crm_tag.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=wedding_planner",
}
