{
    'name': 'Toy Store',
    'version': '1.2',
    'category': 'Retail',
    'depends': [
        'appointment',
        'base_industry_data',
        'point_of_sale',
        'purchase_stock',
        'stock',
        'website',
        'website_appointment',
        'website_sale',
        'website_sale_loyalty',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/product_public_category.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/product_tag.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_product.xml',
        'data/product_image.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/ir_attachment_post.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/product_template.xml',
        'demo/product_attribute_value.xml',
        'demo/product_template_attribute_line.xml',
        'demo/stock_quant.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_reward.xml',
        'demo/loyalty_rule.xml',
        'demo/loyalty_card.xml',
        'demo/website/website.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/the_store.xml',
        'demo/website/pages/board_game_nights.xml',
        'demo/website/pages/home.xml',
        'demo/website/menu.xml',
        'demo/website/images.xml',
        'demo/website/assets.xml',
        'demo/appointment_type.xml',
        'demo/appointment_slot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website/server_actions.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'toy_store/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "demo/website/pages/*.xml",
        "demo/website/views/website_templates.xml",
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=toy_store",
    'website': "https://www.odoo.com/industries/toy-store",
}
