{
    'name': 'Sport Events',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'documents_sign',
        'event_crm',
        'hr_expense',
        'knowledge',
        'project_enterprise',
        'purchase_stock',
        'sale_planning',
        'survey',
        'website_event_booth_sale',
        'website_event_exhibitor',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_tag.xml',
        'data/project_tags.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/spreadsheet_template.xml',
        'data/event_booth_category.xml',
        'data/ir_attachment_pre.xml',
        'data/hr_job.xml',
        'data/res_partner_category.xml',
        'data/crm_stage.xml',
        'data/documents_document.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_document.xml',
        'data/sign_item.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/survey_survey.xml',
        'demo/website_view.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/stock_location.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/planning_slot_template.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_sponsor.xml',
        'demo/event_booth.xml',
        'demo/event_question.xml',
        'demo/event_question_answer.xml',
        'demo/sale_order_line.xml',
        'demo/stock_quant.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/purchase_order_post.xml',
        'demo/sign_request.xml',
        'demo/mail_activity.xml',
        'demo/hr_expense.xml',
        'demo/hr_expense_post.xml',
        'demo/mail_message.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'sport_events/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=sport_events",
    'website': "https://www.odoo.com/all-industries",
}
