{
    'name': 'Sport Events',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account_followup',
        'crm_enterprise',
        'documents_account',
        'documents_hr',
        'documents_hr_expense',
        'documents_product',
        'documents_project',
        'documents_sign',
        'documents_spreadsheet',
        'event_crm',
        'hr_homeworking',
        'hr_sign',
        'hr_skills_survey',
        'knowledge',
        'project_enterprise',
        'sale_crm',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_project_stock',
        'sale_purchase_project',
        'sale_purchase_stock',
        'stock_barcode',
        'website_crm',
        'website_documents',
        'website_event_booth_sale',
        'website_event_sale',
        'website_sale_stock',
        'website_event_booth_exhibitor',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/spreadsheet_template.xml',
        'data/ir_attachment_pre.xml',
        'data/hr_job.xml',
        'data/res_partner_category.xml',
        'data/stock_warehouse.xml',
        'data/crm_stage.xml',
        'data/documents_document.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/product_attribute.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/product_public_category.xml',
        'data/project_task_type.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        # 'data/sign_item.xml',
        # 'data/sign_template.xml',
        # 'data/sign_request.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/crm_tag.xml',
        'demo/crm_team.xml',
        'demo/survey_survey.xml',
        'demo/documents_document.xml',
        'demo/website_view.xml',
        'demo/hr_department.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/planning_slot_template.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/event_booth_category.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_sponsor.xml',
        'demo/event_booth.xml',
        'demo/sale_order_line.xml',
        'demo/stock_location.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/purchase_order_post.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'sport_events/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
}
