{
    'name': 'Coworking',
    'version': '1.1',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'crm_enterprise',
        'delivery',
        'hr_sign',
        'knowledge',
        'mass_mailing',
        'partnership',
        'planning',
        'product',
        'sale_subscription',
        'survey',
        'website',
        'website_appointment',
        'website_event',
        'website_event_sale',
        'website_helpdesk',
        'website_sale',
        'website_sale_loyalty',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/crm_stage.xml',
        'data/product_category.xml',
        'data/website_product_category.xml',
        'data/uom_uom.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/planning_slot_template.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product_variant.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/product_pricelist_item.xml',
        'data/product_pricelist_item_subscription.xml',
        'data/crm_tag.xml',
        'data/hr_job.xml',
        'data/helpdesk_team.xml',
        'data/mailing_mailing.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/ir_attachment_business.xml',
    ],
    'demo': [
        'demo/loyalty_program.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/loyalty_rule.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website_event_event.xml',
        'demo/website/website.xml',
        'demo/helpdesk_team.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/server_actions.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/pricing.xml',
        'demo/website/pages/membership.xml',
        'demo/website/pages/about.xml',
        'demo/website/pages/latest_events.xml',
        'demo/website/menu.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/server_actions_dynamic_filters.xml',
        'demo/website/server_actions_links.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=coworking",
    'website': "https://www.odoo.com/all-industries",
}
