{
    'name': 'Coworking',
    'version': '1.0',
    'category': 'Service',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'hr_sign',
        'knowledge',
        'mass_mailing',
        'partnership',
        'planning',
        'sale_subscription',
        'survey',
        'website_appointment',
        'website_event_sale',
        'website_helpdesk',
        'website_sale_loyalty',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/crm_stage.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/planning_slot_template.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/product_pricelist_item.xml',
        'data/crm_tag.xml',
        'data/hr_job.xml',
        'data/event_event.xml',
        'data/helpdesk_team.xml',
        'data/mailing_mailing.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/product_product.xml',
        'demo/loyalty_program.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/helpdesk_team.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/loyalty_rule.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=coworking",
}
