{
<<<<<<< af1e9687b784b483301897d6dc1b33259853187f
    'name': 'Sports Facilities',
    'version': '1.7',
    'category': 'Health and Fitness',
||||||| e5a1ba433a012ad0dcff740c631f8f97783d2861
    'name': 'Sports Club',
    'version': '1.0',
    'category': 'Health and Fitness',
    'description': """
        This setup is for sports clubs that rent courts to their players, handle some basic gears and have a cafeteria.
        As a small company, The Club still has quite a lot of activities to manage and does all this with Odoo.
    """,
=======
    'name': 'Sports Club',
    'version': '1.0',
    'category': 'Events, Community and Nonprofits',
    'description': """
        This setup is for sports clubs that rent courts to their players, handle some basic gears and have a cafeteria.
        As a small company, The Club still has quite a lot of activities to manage and does all this with Odoo.
    """,
>>>>>>> 20014fd4a7f3eef3b4149c7cb00d24f3495f074a
    'depends': [
        'appointment_crm',
        'frontdesk_partnership',
        'knowledge',
        'loyalty',
        'planning',
        'pos_restaurant',
        'sale_subscription',
        'website_appointment',
        'website_crm',
        'website_sale',
    ],
    'data': [
        'data/product_pricelist.xml',
        'data/res_config_settings.xml',
        'data/pos_category.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/pos_config.xml',
        'data/pos_prep_display.xml',
        'data/ir_attachment_pre.xml',
        'data/product_public_category.xml',
        'data/planning_role.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/resource_calendar.xml',
        'data/frontdesk.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/knowledge_tour.xml',
        'data/ir_ui_menu.xml'
    ],
    'demo': [
        'demo/delivery_carrier.xml',
        'demo/res_company.xml',
        'demo/product_pricelist_item.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/product_template.xml',
        'demo/product_product.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/planning_slot.xml',
        'demo/appointment_invite.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website_ir_attachments.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'application': True,
    'images': ['images/main.png'],
    'assets': {
        'web.assets_backend': [
            'sports_club/static/src/js/my_tour.js',
        ],
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        'demo/website_view.xml',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=sports_club",
    'website': "https://www.odoo.com/industries/sports-club",
}
