{
    'name': 'Sports Facilities',
    'version': '1.4',
    'category': 'Health and Fitness',
    'depends': [
        'appointment_crm',
        'frontdesk_partnership',
        'knowledge',
        'loyalty',
        'planning',
        'pos_restaurant',
        'sale_subscription',
        'website_appointment',
        'website_crm',
        'website_sale',
    ],
    'data': [
        'data/product_pricelist.xml',
        'data/res_config_settings.xml',
        'data/pos_category.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/pos_config.xml',
        'data/pos_prep_display.xml',
        'data/ir_attachment_pre.xml',
        'data/product_public_category.xml',
        'data/planning_role.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/resource_calendar.xml',
        'data/frontdesk.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/knowledge_tour.xml',
        'data/ir_ui_menu.xml'
    ],
    'demo': [
        # The website record must come first: everything below resolves
        # base.default_website, which demo/website/website.xml re-points to it.
        'demo/website/website.xml',
        'demo/product_pricelist.xml',
        'demo/delivery_carrier.xml',
        'demo/res_company.xml',
        'demo/product_pricelist_item.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/product_template.xml',
        'demo/product_product.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/planning_slot.xml',
        'demo/appointment_type.xml',
        'demo/appointment_invite.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        # Website: views before the pages, server_actions last (it rewrites
        # the arch of the views the page files create).
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        "demo/website/views/website_sale_templates.xml",
        'demo/website/pages/home.xml',
        'demo/website/pages/our_club.xml',
        'demo/website/pages/products.xml',
        'demo/website/pages/coaches.xml',
        'demo/website/pages/contactus.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website/server_actions.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'application': True,
    'images': ['images/main.png'],
    'assets': {
        'web.assets_backend': [
            'sports_club/static/src/js/my_tour.js',
        ],
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "static/src/scss/primary_variables.scss",
        "demo/website/views/website_templates.xml",
        "demo/website/views/website_sale_templates.xml",
        "demo/website/pages/home.xml",
        "demo/website/pages/our_club.xml",
        "demo/website/pages/products.xml",
        "demo/website/pages/coaches.xml",
        "demo/website/pages/contactus.xml",
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=sports_club",
    'website': "https://www.odoo.com/industries/sports-club",
}
