{
    'name': 'Bar & Pub',
    'version': '1.0',
    'category': 'Hospitality',
    'depends': [
        'account_followup',
        'hr_attendance',
        'hr_hourly_cost',
        'hr_skills',
        'knowledge',
        'loyalty',
        'planning',
        'point_of_sale',
        'pos_restaurant',
        'pos_self_order',
        'project_enterprise',
        'purchase_stock',
        'stock_account',
    ],
    'data': [
        'data/res_partner.xml',
        'data/hr_department.xml',
        'data/hr_employee.xml',
        'data/pos_config.xml',
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/project_project.xml',
        'data/planning_role.xml',
        'data/product_pricelist.xml',
        'data/pos_category.xml',
        'data/uom_uom.xml',
        'data/product_product.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/pos_preparation_display_display.xml',
        'demo/planning_slot_template.xml',
        'demo/product_product.xml',
        'demo/product_pricelist_item.xml',
        'demo/product_supplierinfo.xml',
        'demo/project_task.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'bar_industry/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
