{
    'name': 'Beauty Parlor',
    'version': '1.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'account_online_payment',
        'google_calendar',
        'knowledge',
        'loyalty',
        'pos_enterprise',
        'sale',
        'survey',
        'website_appointment_crm',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/crm_stage.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/loyalty_program.xml',
        'demo/website_view.xml',
        'demo/email_template.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/res_partner.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/website_theme_apply.xml',
        'demo/website_page.xml',
        'demo/crm_lead.xml',
        'demo/loyalty_rule.xml',
        'demo/mail_activity.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/loyalty_reward.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'beauty_parlor/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=beauty_parlor",
    'website': "https://www.odoo.com/all-industries",
}
