{
    'name': 'Gallery',
    'version': '1.4',
    'category': 'Retail',
    'depends': [
        'base_industry_data',
        'partner_commission',
        'pos_sale',
        'sale_purchase_project',
        'sign',
        'website_blog',
        'website_event_sale',
    ],
    'data': [
        'data/crm_stage.xml',
        'data/ir_ui_menu.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/res_config_settings.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/ir_attachment.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/res_partner_grade.xml',
        'data/crm_tag.xml',
        'data/commission_plan.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/product_template.xml',
        'demo/res_partner_category.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/blog_blog.xml',
        'demo/blog_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/website/website.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/artists.xml',
        'demo/website/pages/exhibitions.xml',
        'demo/website/pages/info.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/server_actions.xml',
    ],
    'author': 'Odoo S.A.',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/blog_blog.xml',
        'demo/blog_post.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/artists.xml',
        'demo/website/pages/exhibitions.xml',
        'demo/website/pages/info.xml',
        'demo/website/pages/contactus.xml',
        'static/src/scss/primary_variables.scss',
    ],
    'application': True,
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=gallery",
    'website': "https://www.odoo.com/all-industries",
}
