{
  'name': 'Gallery',
  'version': '1.0',
  'category': 'Retail',
  'depends': [
        'knowledge',
        'partner_commission',
        'pos_sale',
        'sale_purchase_project',
        'sign',
        'website_event_sale'
  ],
  'data': [
        'data/crm_stage.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/res_config_settings.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/ir_attachment.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/res_partner_grade.xml',
        'data/crm_tag.xml',
        'data/commission_plan.xml',
  ],
  'demo': [
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml'
  ],
  'assets': {
        'web.assets_backend': [
            'gallery/static/src/js/my_tour.js',
        ]
  },
  'author': 'Odoo S.A.',
  "cloc_exclude": [
      "data/knowledge_article.xml",
      "static/src/js/my_tour.js",
      "demo/website_view.xml",
  ],
  'images': ['images/main.png'],
  'license': 'OPL-1'
}
