{
    'name': 'Fine Dining Restaurant',
    'version': '1.1',
    'category': 'Hospitality',
    'depends': [
        'account_followup',
        'base_industry_data',
        'contacts',
        'hr_attendance',
        'knowledge',
        'planning',
        'pos_enterprise',
        'pos_loyalty',
        'pos_online_payment_self_order',
        'pos_restaurant_appointment',
        'project',
        'purchase_stock',
        'website_appointment',
    ],
    'data': [
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/res_config_settings.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_default_data.xml',
        'data/uom_uom.xml',
        'data/product_product.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/resource_calendar_data.xml',
        'demo/pos_payment_method.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/planning_role.xml',
        'demo/planning_slot_templates.xml',
        'demo/pos_config.xml',
        'demo/pos_category.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_product.xml',
        'demo/stock_quant.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/kitchen_display.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/planning_slot.xml',
        'demo/project_task.xml',
        'demo/website_attachment.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/pos_orders.xml',
        'demo/pos_order_lines.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=industry_restaurant",
    'website': "https://www.odoo.com/industries/fine-dining-restaurant",
}
