# -*- coding: utf-8 -*-
{
    'name': 'Restaurant (Foods & Cafes)',
    'version': '1.0',
    'category': 'Industry',
    'description': """
        This Odoo module is designed to streamline and enhance the management of your restaurant operations.
        Whether you own a fine dining establishment, a cafe, or a fast-food joints, cafés, food trucks, Cloud kitchen, and more.
    """,
    'author': 'Odoo SA',
    'depends': [
        'account_check_printing',
        'account_followup',
        'account_online_synchronization',
        'hr_hourly_cost',
        'knowledge',
        'mrp_account',
        'planning',
        'pos_enterprise',
        'pos_epson_printer',
        'pos_hr',
        'pos_loyalty',
        'pos_online_payment_self_order',
        'project_sms',
        'purchase_mrp',
        'sale_purchase',
        'survey',
        'website_appointment',
        'website_sale_loyalty',
        'website_sale_product_configurator',
        'website_sale_stock'
    ],
    'data': [
        'data/res_config.xml',
        'data/ir_attachment_pre.xml',
        'data/account_cash_rounding.xml',
        'data/product_public_category.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_member.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/pos_config.xml',
        'data/appointment_resource.xml',
        'data/appointment_type.xml',
    ],
    'demo': [
        'demo/appointment_type.xml',
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/pos_confirm.xml',
        'demo/pos_preparation_display.xml',
        'demo/pos_preparation_display_order.xml',
        'demo/pos_preparation_display_orderline.xml',
        'demo/pos_preparation_display_confirm.xml',
    ],
    'application': False,
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
