{
    "name": "Community Care",
    "category": "Services",
    "author": "Odoo S.A.",
    "depends": [
        "ai_documents",
        "ai_knowledge",
        "ai_server_actions",
        "appointment",
        "contacts",
        "documents_fleet",
        "documents_hr",
        "documents_project_sign",
        "google_calendar",
        "hr_sign",
        "hr_skills",
        "iap_extract",
        "knowledge",
        "planning_holidays",
        "project_holidays",
        "spreadsheet_dashboard_documents",
        "survey",
        "timesheet_grid_holidays",
        "web_studio",
    ],
    "data": [
        "data/ir_model.xml",
        "data/ir_model_fields.xml",
        "data/ir_ui_view.xml",
        "data/ir_actions_act_window.xml",
        "data/ir_actions_server.xml",
        "data/ir_ui_menu.xml",
        "data/base_automation.xml",
        "data/ir_model_access.xml",
        "data/documents_document.xml",
        "data/knowledge_article.xml",
        "data/resource_calendar.xml",
        "data/resource_calendar_attendance.xml",
        "data/resource_resource.xml",
        "data/res_config_settings.xml",
        "data/planning_role.xml",
        "data/x_allergy.xml",
        "data/x_contact_nature.xml",
        "data/x_languages.xml",
        "data/x_res_partner_line.xml",
        "data/mail_message.xml",
        "data/knowledge_article_favorite.xml",
    ],
    "demo": [
        "demo/knowledge_article.xml",
        "demo/res_partner.xml",
        "demo/x_languages.xml",
        "demo/x_allergy.xml",
        "demo/calendar_event.xml",
        "demo/planning_slot_template.xml",
        "demo/planning_slot.xml",
        "demo/documents_document.xml",
        "demo/hr_employee.xml",
        "demo/hr_leave.xml",
        "demo/x_res_partner_line.xml",
    ],
    "license": "OEEL-1",
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    "images": ["images/main.png"],
    "url": "https://www.odoo.com/trial?industry&selected_app=community_care",
    "website": "https://www.odoo.com/all-industries",
}
