{
    'name': 'Community Care',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account',
        'appointment',
        'base_industry_data',
        'calendar',
        'contacts',
        'documents_project_sign',
        'hr_sign',
        'knowledge',
        'planning_holidays',
        'project_holidays',
        'sale',
        'spreadsheet_dashboard_documents',
        'spreadsheet_dashboard_hr_timesheet',
        'timesheet_grid_holidays',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_default.xml',
        'data/ir_actions_server.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/documents_document.xml',
        'data/knowledge_article.xml',
        'data/resource_calendar.xml',
        'data/resource_calendar_attendance.xml',
        'data/resource_resource.xml',
        'data/res_config_settings.xml',
        'data/planning_role.xml',
        'data/x_allergy.xml',
        'data/x_languages.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/x_family_unit.xml',
        'data/x_stay.xml'
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/hr_employee.xml',
        'demo/res_partner.xml',
        'demo/knowledge_article.xml',
        'demo/x_languages.xml',
        'demo/x_allergy.xml',
        'demo/x_stay.xml',
        'demo/calendar_event.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/documents_document.xml',
        'demo/hr_leave.xml',
        'demo/spreadsheet_dashboard_group.xml',
        'demo/spreadsheet_dashboard.xml',
        'demo/x_shortcut.xml',
        'demo/product_product.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'community_care/static/src/js/list_optional_columns_patch.js'
        ]
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/knowledge_article.xml',
        'static/src/js/list_optional_columns_patch.js'
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': 'https://www.odoo.com/trial?industry&selected_app=community_care',
    'website': 'https://www.odoo.com/all-industries',
}
