{
    'name': 'Tattoo Shop',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'base_automation',
        'crm_enterprise',
        'knowledge',
        'sale_planning',
        'sale_purchase',
        'sale_service',
        'sign',
        'social',
        'web_studio',
        'website',
    ],
    'data': [
        'data/crm_tag.xml',
        'data/ir_attachment_pre.xml',
        'data/appointment_type.xml',
        'data/mail_template.xml',
        'data/mail_activity_type.xml',
        'data/crm_stage.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favourite.xml',
        'data/product_product.xml',
        'data/sign_template_tag.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
    ],
    'demo': [
        'demo/appointement_type.xml',
        'demo/ir_attachment_post.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/website_views.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'tattoo_shop/static/src/js/my_tour.js',
        ]
    },
    'cloc_exclude': [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        'demo/website_views.xml',
    ],
    'images': ['images/main.png'],
    'license': 'OEEL-1',
}
