{
    'name': 'Holiday House',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'booking_engine',
        'web_studio',
    ],
    'data': [
        'data/planning_role.xml',
        'data/resource_resource.xml',
        'data/product_template.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_image.xml',
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/views.xml',
        'data/web_views.xml',
        'data/product_pricing.xml',
    ],
    'demo': [
        'demo/product_template_post.xml',
        'demo/rating_rating.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/web_views.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=holiday_house",
    'website': "https://www.odoo.com/all-industries",
}
