{
    'name': 'Catering',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'hr_skills',
        'knowledge',
        'planning',
        'project_forecast',
        'purchase_stock',
        'sale_management',
        'sale_timesheet',
        'stock_dropshipping',
        'survey',
        'website',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/ir_attachment_pre.xml',
        'data/mail_template.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/ir_ui_menu.xml',
    ],
    'demo': [
        'demo/crm_tag.xml',
        'demo/res_partner.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_picking.xml',
        'demo/stock_move.xml',
        'demo/project_project.xml',
        'demo/project_task.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/planning_slot_template.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/product_supplierinfo.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=catering",
    'website': "https://www.odoo.com/all-industries",
}
