{
    'name': 'Student Organization',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'documents_hr_expense',
        'event',
        'knowledge',
        'partnership',
        'point_of_sale',
        'project_enterprise',
        'purchase',
        'sale_crm',
        'sale_planning',
        'sign',
        'social',
        'survey',
        'website_crm',
        'website_event_sale',
        'website_sale_mass_mailing',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/documents_document.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/mailing_mailing.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_pricelist_item.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/sale_order.xml',
        'demo/documents_document.xml',
        'demo/hr_department.xml',
        'demo/account_analytic_plan.xml',
        'demo/purchase_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/sale_order_line.xml',
        'demo/hr_employee.xml',
        'demo/hr_expense.xml',
        'demo/hr_expense_action.xml',
        'demo/event_event.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'student_organization/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
