{
    'name': 'Student Organization',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'documents_sign',
        'hr_expense',
        'knowledge',
        'partnership',
        'pos_enterprise',
        'project_enterprise',
        'purchase',
        'social',
        'website_event_sale',
        'website_sale_mass_mailing',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/documents_document.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/mailing_filter.xml',
        'data/mailing_mailing.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_pricelist_item.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/sale_order.xml',
        'demo/purchase_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/sale_order_line.xml',
        'demo/hr_employee.xml',
        'demo/hr_expense.xml',
        'demo/hr_expense_action.xml',
        'demo/event_event.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=student_organization",
    'website': "https://www.odoo.com/all-industries",
}
