{
    'name': 'Libraries',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'crm',
        'event',
        'hr_homeworking',
        'hr_hourly_cost',
        'knowledge',
        'partnership',
        'pos_enterprise',
        'sale_subscription',
        'sale_service',
        'web_studio',
        'website_event_sale',
        'website_sale_collect',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/stock_route.xml',
        'data/stock_location.xml',
        'data/stock_picking_type.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/event.event.xml',
        'data/mail_template.xml',
        'data/ir_ui_menu.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_product.xml',
        'data/product_template.xml',
        'data/product_pricelist.xml',
        # 'data/product_attribute.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/ir_filters.xml',
        'data/res_partner_grade.xml',
        'data/stock_rule.xml',
        'data/delivery_carrier.xml',
    ],
    'demo': [
        'demo/payment_provider_demo.xml',
        'demo/product_pricelist.xml',
        'demo/product_product.xml',
        'demo/event_event.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/hr_department.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
