{
<<<<<<< af1e9687b784b483301897d6dc1b33259853187f
    'name': 'Clothing Stores',
    'version': '1.4',
    'category': 'Retail',
    'author': 'Odoo S.A.',
||||||| e5a1ba433a012ad0dcff740c631f8f97783d2861
    'name': 'Clothing Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This setup if for Clothing Store companies selling female clothing.""",
=======
    'name': 'Clothing Store',
    'version': '1.0',
    'category': 'Retail and eCommerce',
    'description': """
This setup if for Clothing Store companies selling female clothing.""",
>>>>>>> 20014fd4a7f3eef3b4149c7cb00d24f3495f074a
    'depends': [
        'base_industry_data',
        'loyalty',
        'mass_mailing',
        'pos_enterprise',
        'purchase',
        'sale_project',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_public_category.xml',
        'data/product_ribbon.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_image.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/website.xml',
    ],
    'demo': [
        'demo/mailing_mailing.xml',
        'demo/product_template.xml',
        'demo/loyalty_program.xml',
        'demo/sale_order.xml',
        'demo/res_partner.xml',
        'demo/res_company.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/loyalty_rule.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order_line.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_session.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=clothing_boutique",
    'website': "https://www.odoo.com/industries/clothing-store",
}
