{
    'name': 'Clothing Boutique',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'account_add_gln',
        'account_online_payment',
        'hr_homeworking',
        'hr_sign',
        'hr_skills',
        'knowledge',
        'l10n_be_reports',
        'pos_enterprise',
        'pos_loyalty',
        'pos_online_payment',
        'pos_planning',
        'project_enterprise',
        'project_purchase',
        'sale_account_accountant',
        'sale_loyalty_delivery',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_purchase_stock',
        'stock_barcode',
        'survey',
        'website_appointment_sale_project',
        'website_sale_autocomplete',
        'website_sale_comparison',
        'website_sale_loyalty',
        'website_sale_mass_mailing',
        'website_sale_stock_wishlist',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_image.xml',
        'data/project_task_type.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/loyalty_program.xml',
        'demo/sale_order.xml',
        'demo/resource_resource.xml',
        'demo/project_task.xml',
        'demo/res_partner.xml',
        'demo/website_view.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/stock_quant.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/loyalty_rule.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order_line.xml',
        'demo/purchase_order.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_session.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "demo/website_view.xml",
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=clothing_boutique",
    'website': "https://www.odoo.com/industries/clothing-store",
}
