{
    'name': 'Interior Design',
    'version': '1.1',
    'category': 'Construction',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'documents_sign',
        'planning_field_service_sale_timesheet',
        'project_purchase',
        'sale_crm',
        'website_sale',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/crm_team.xml',
        'data/mail_template.xml',
        'data/documents_document.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/planning_role.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_product.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/project_tags.xml',
        'data/mail_message.xml',
        'data/planning_slot_template.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/payment_provider_demo.xml',
        'demo/res_partner.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/appointment_question.xml',
        'demo/appointment_type.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/product_supplierinfo.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/sign_template.xml',
        'demo/sign_item_role.xml',
        'demo/sign_document.xml',
        'demo/sign_item.xml',
        'demo/sign_request.xml',
        'demo/documents_document.xml',
        'demo/project_project.xml',
        'demo/project_task.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'application': True,
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=interior_design",
    'website': "https://www.odoo.com/all-industries",
}
