{
    'name': 'Electronic Refurbishment',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'accountant',
        'base_industry_data',
        'contacts',
        'knowledge',
        'product_conversion',
        'product_margin',
        'purchase_mrp',
        'sale_management',
        'web_studio',
        'website_appointment',
        'website_sale',
    ],
    'data': [
        'data/account_tax.xml',
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_image.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/product_template.xml',
        'demo/res_users.xml',
        'demo/rating_rating.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/mrp_production.xml',
        'demo/stock_move.xml',
        'demo/mrp_production_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'application': True,
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': 'https://www.odoo.com/trial?industry&selected_app=electronic_refurbishment',
    'website': 'https://www.odoo.com/all-industries',
}
