{
    'name': 'Pet Groomers',
    'version': '1.0',
    'category': 'Trades & Home Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'hr_skills',
        'knowledge',
        'pos_enterprise',
        'purchase_stock',
        'sale_management',
        'web_studio',
        'website_appointment_crm',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model.xml',
        'data/product_category.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_server.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/product_product.xml',
        'data/product_tag.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/x_allergies.xml',
        'data/x_medical_issues.xml',
        'data/x_species.xml',
        'data/x_species_line.xml',
        'data/x_pets.xml',
        'data/x_treatments.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/crm_tag.xml',
        'demo/hr_job.xml',
        'demo/res_partner.xml',
        'demo/x_pets.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/hr_employee.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/stock_quant.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
