{
    'name': 'Yoga & Pilates Studio',
    'version': '1.0',
    'category': 'Health and Fitness',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'base_industry_data',
        'hr_skills_survey',
        'knowledge',
        'partnership',
        'sale_planning',
        'website_appointment_sale',
        'website_crm',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/appointment_resource.xml',
        'data/product_category.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/product_pricelist_item.xml',
        'data/appointment_type.xml',
        'data/ir_attachment_post.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/mail_template.xml',
        'data/planning_role.xml',
        'data/hr_job.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/appointment_type.xml',
        'demo/event_event.xml',
        'demo/product_product.xml',
        'demo/hr_department.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_reward.xml',
        'demo/loyalty_rule.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/survey_survey.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
