{
    'name': 'Cleaning Services',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_sale_subscription',
        'hr',
        'industry_fsm_sale',
        'knowledge',
        'project_purchase',
        'project_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task_recurrence.xml',
        'data/sale_subscription_plan.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_product.xml',
        'data/crm_tag.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/res_config_settings.xml',
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_analytic_line.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
