{
    'name': 'Cleaning Services',
    'version': '1.0',
    'category': 'Services',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'account_online_synchronization',
        'crm_sale_subscription',
        'hr_skills',
        'industry_fsm_sale_report',
        'project_purchase',
        'project_sale_subscription',
        'knowledge',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/worksheet_template.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task_recurrence.xml',
        'data/sale_subscription_plan.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/account_analytic_account.xml',
        'demo/res_partner.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/sale_order_state.xml',
        'demo/account_analytic_line.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/project_project.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cleaning_services/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
