{
    'name': 'Public Institution',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account_followup',
        'base_industry_data',
        'documents_project',
        'hr_sign',
        'knowledge',
        'survey',
        'website_appointment',
        'website_blog',
        'website_event',
        'website_helpdesk',
        'website_sale_renting_planning',
    ],
    'data': [
        'data/appointment_type.xml',
        'data/knowledge_article.xml',
        'data/helpdesk_team.xml',
        'data/planning_role.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/knowledge_article.xml',
        'demo/knowledge_article_update.xml',
        'demo/knowledge_article_favorite.xml',
        'demo/product_product.xml',
        'demo/res_users.xml',
        'demo/appointment_type.xml',
        'demo/survey_survey.xml',
        'demo/res_partner.xml',
        'demo/res_company.xml',
        'demo/website_view.xml',
        'demo/resource_resource.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/hr_employee.xml',
        'demo/hr_department.xml',
        'demo/planning_slot_template.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_tags.xml',
        'demo/project_task_type.xml',
        'demo/project_project.xml',
        'demo/project_task.xml',
        'demo/event_tag_category.xml',
        'demo/event_tag.xml',
        'demo/event_event.xml',
        'demo/sign_template.xml',
        'demo/sign_item.xml',
        'demo/blog_blog.xml',
        'demo/blog_tag.xml',
        'demo/blog_post.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/helpdesk_team.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'application': True,
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=public_institution",
    'website': "https://www.odoo.com/all-industries",
}
