{
    'name': 'Electronic Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
        This module provides essential features to manage an electronic store.
        It includes product categories, products, sales orders, and more for electronic products.
    """,
    'depends': [
        'account_followup',
        'appointment_crm',
        'documents_fsm',
        'documents_project_sale',
        'helpdesk_account',
        'helpdesk_repair',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'pos_sale',
        'product_expiry',
        'purchase_stock',
        'sale_purchase',
        'stock_barcode',
        'website_sale_loyalty',
        'theme_buzzy',
    ],
    'data': [
        'data/helpdesk_config.xml',
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/product_public_category.xml',
        'data/documents_folder.xml',
        'data/product_category.xml',
        'data/worksheet_template.xml',
        'data/account_analytic_plan.xml',
        'data/account_analytic_account.xml',
        'data/project_project.xml',
        'data/project_task_type.xml',
        'data/uom_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
    ],
    'demo': [
        'demo/project_task.xml',
        'demo/x_worksheet_template.xml',
        'demo/helpdesk_ticket.xml',
        'demo/website_ir_attachment.xml',
        'demo/website.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_post.xml',
        'demo/crm_lead_post.xml',
        'demo/website_theme_apply.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
