{
    'name': 'Electronic Store',
<<<<<<< 44142a93dfc6489c665550932c07f6317434cdf6
    'version': '1.1',
    'category': 'Retail',
||||||| e5a1ba433a012ad0dcff740c631f8f97783d2861
    'version': '1.0',
    'category': 'Retail',
    'description': """
        This module provides essential features to manage an electronic store.
        It includes product categories, products, sales orders, and more for electronic products.
    """,
=======
    'version': '1.0',
    'category': 'Retail and eCommerce',
    'description': """
        This module provides essential features to manage an electronic store.
        It includes product categories, products, sales orders, and more for electronic products.
    """,
>>>>>>> 20014fd4a7f3eef3b4149c7cb00d24f3495f074a
    'depends': [
        'crm',
        'documents_project_sale',
        'helpdesk_account',
        'helpdesk_repair',
        'knowledge',
        'planning_field_service_sale_stock',
        'planning_field_service_sale_worksheet',
        'point_of_sale',
        'purchase_stock',
        'sale_management',
        'sale_purchase',
        'stock_barcode',
        'web_studio',
        'website_sale',
    ],
    'data': [
        'data/helpdesk_config.xml',
        'data/res_config_settings.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/product_public_category.xml',
        'data/documents_folder.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/worksheet_template.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/res_partner.xml',
        'demo/account_analytic_plan.xml',
        'demo/account_analytic_account.xml',
        'demo/helpdesk_ticket.xml',
        'demo/repair_order.xml',
        'demo/website_ir_attachment.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_product.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/stock_lot.xml',
        'demo/stock_warehouse.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_post.xml',
        'demo/crm_lead_post.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/pos_confirm.xml',
        'demo/website_theme_apply.xml',
        'demo/planning_slot.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'electronic_store/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=electronic_store",
    'website': "https://www.odoo.com/industries/electronics-store",
}
