{
    'name': 'Concert Halls',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'event_crm',
        'event_sale',
        'hr',
        'knowledge',
        'pos_event',
        'pos_online_payment',
        'project_enterprise',
        'sale_crm',
        'social',
        'website_crm',
        'website_event',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_config.xml',
        'data/pos_payment_method.xml',
        'data/product_public_category.xml',
        'data/project_task_type.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/crm_tag.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/event_event.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/pos_session.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
