{
    'name': 'Concert Halls',
    'version': '1.5',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm',
        'event_sale',
        'pos_event',
        'pos_restaurant',
        'project_enterprise',
        'social',
        'website_event',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/ir_ui_menu.xml',
        'data/crm_tag.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_config.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/website/website.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/views/website_event_templates.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/business.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/server_actions.xml',
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/views/website_event_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/business.xml',
        'demo/website/pages/contactus.xml',
        'static/src/scss/primary_variables.scss',
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=concert_halls",
    'website': "https://www.odoo.com/all-industries",
}
