{
    'name': 'Concert Halls',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'event_sale',
        'knowledge',
        'pos_event',
        'project_enterprise',
        'social',
        'website_crm',
        'website_event',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/crm_tag.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_config.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
    ],
    'demo': [
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=concert_halls",
    'website': "https://www.odoo.com/all-industries",
}
