{
    'name': 'Cosmetics Store',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'calendar',
        'contacts',
        'hr',
        'knowledge',
        'loyalty',
        'pos_enterprise',
        'purchase',
        'sale_service',
        'website_sale_collect',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_image.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/payment_provider_demo.xml',
        'demo/stock_quant.xml',
        'demo/product_template.xml',
        'demo/loyalty_program.xml',
        'demo/hr_job.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/pos_order.xml',
        'demo/purchase_order_confirm.xml',
        'demo/loyalty_reward.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/loyalty_rule.xml',
        'demo/hr_employee.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'cosmetics_store/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
        'static/src/js/my_tour.js',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=cosmetics_store",
    'website': "https://www.odoo.com/all-industries",
}
