{
    'name': 'Event Management',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'documents_project',
        'hr_recruitment_skills',
        'knowledge',
        'maintenance',
        'project_purchase',
        'purchase_requisition',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_purchase_stock',
        'sale_stock_renting',
        'sign',
        'spreadsheet_sale_management',
        'website_crm',
        'website_event',
        'website_hr_recruitment',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/crm_tag.xml',
        'data/documents_document.xml',
        'data/project_project_stage.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/uom_uom.xml',
        'data/product_pricing.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/ir_attachment_post.xml',
        'data/res_partner_category.xml',
        'data/stock_location.xml',
        'data/hr_job.xml',
        'data/planning_role.xml',
        'data/planning_slot_template.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/event_slot.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/hr_job.xml',
        'demo/documents_document.xml',
        'demo/crm_lead.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/event_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_requisition.xml',
        'demo/purchase_requisition_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_line.xml',
        'demo/knowledge_article.xml',
        'demo/knowledge_article_favorite.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/maintenance_request.xml',
        'demo/mail_message.xml',
        'demo/project_task.xml',
        'demo/mail_activity.xml',
        'demo/stock_quant.xml',
        'demo/website_view.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
