{
    'name': 'Bike Hub',
    'version': '2.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'calendar',
        'crm',
        'helpdesk',
        'planning_field_service',
        'point_of_sale',
        'project',
        'purchase_stock',
        'sale_timesheet',
        'website_sale_subscription',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/res_config_settings.xml',
        'data/appointment_type.xml',
        'data/helpdesk_team.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/payment_provider_demo.xml',
        'demo/hr_department.xml',
        'demo/product_template.xml',
        'demo/pos_session.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/res_partner.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/appointment_type.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'data/product_template.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/mail_activity.xml',
        'demo/product_supplierinfo.xml',

        'demo/ir_attachment_post.xml',
        'demo/website/website.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        # Must load before `server_actions.xml`: it activates three of the keys
        # this file overrides. Loading it first means the server action writes
        # `active` on these views instead of COW'ing a second view on the same key.
        'demo/website/views/website_templates.xml',
        'demo/website/server_actions.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/about.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/maintenance_repairs.xml',

        'demo/mail_alias.xml',
        'demo/helpdesk_team.xml',
        'demo/helpdesk_ticket.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/about.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/maintenance_repairs.xml',
        'static/src/scss/primary_variables.scss',
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=bike_shop",
    'website': "https://www.odoo.com/all-industries",
}
