{
    'name': 'Bike Shop',
    'version': '1.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_google_calendar',
        'appointment_hr',
        'helpdesk_fsm',
        'helpdesk_sale',
        'hr_skills_survey',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'pos_enterprise',
        'pos_hr',
        'pos_online_payment',
        'project_purchase',
        'sale_pdf_quote_builder',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'stock_barcode',
        'web_studio',
        'website_appointment_sale_project',
        'website_helpdesk_knowledge',
        'website_sale_collect',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/qweb_views.xml',
        'data/ir_actions_act_window.xml',
        'data/mail_template.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/pos_payment_method.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/worksheet_template.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/product_attribute.xml',
        'data/product_template.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/project_tags.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/payment_provider_demo.xml',
        'demo/product_template.xml',
        'demo/appointment_type.xml',
        'demo/survey_survey.xml',
        'demo/hr_job.xml',
        'demo/website.xml',
        'demo/account_analytic_account.xml',
        'demo/website_view.xml',
        'demo/hr_department.xml',
        'demo/account_analytic_plan.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/project_project.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/pos_order.xml',
        'demo/helpdesk_ticket.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/hr_employee.xml',
        # 'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
    ],
    'license': 'OPL-1',
    'assets': {
            'web.assets_backend': [
                'bike_shop/static/src/js/my_tour.js',
            ],
        },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'data/qweb_views.xml',
    ],
    'images': [
        'images/main.png',
    ],
}