{
    'name': 'Diy Workshops',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account_followup',
        'crm_enterprise',
        'crm_sale_subscription',
        'event_crm',
        'knowledge',
        'partnership',
        'sale_crm',
        'sale_loyalty_delivery',
        'sale_pdf_quote_builder',
        'sale_purchase',
        'sale_service',
        'spreadsheet_sale_management',
        'survey',
        'website_crm',
        'website_event_sale',
        'website_sale_dashboard',
        'website_sale_loyalty',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/res_partner_grade.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/loyalty_program.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_slot.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/loyalty_rule.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}