{
    'name': 'DIY Workshops',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'knowledge',
        'partnership',
        'purchase',
        'sale_subscription',
        'website_event_sale',
        'website_sale_loyalty',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_pricelist_item.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/website_menu.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_pricelist.xml',
        'demo/product_product.xml',
        'demo/loyalty_program.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/event_slot.xml',
        'demo/sale_order_line.xml',
        'demo/loyalty_rule.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_post.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order_post.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
