{
    'name': 'Construction Developer',
    'version': '1.12',
    'category': 'Construction',
    'depends': [
        'base_industry_data',
        'construction',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',

        # models
        'data/product_cost_nature/ir_model.xml',
        'data/remarks/ir_model.xml',
        'data/work_items/ir_model.xml',
        # fields
        'data/remarks/ir_model_fields.xml',
        'data/sale_order_contract_type/ir_model_fields.xml',
        'data/sale_order_sequencing_and_references/ir_model_fields.xml',
        'data/sale_order_delivery_progress_management/ir_model_fields.xml',
        'data/work_items/ir_model_fields.xml',
        'data/product_cost_nature/ir_model_fields.xml',
        'data/work_item_lines_procurement/ir_model_fields.xml',
        # defaults
        'data/remarks/ir_default.xml',
        'data/sale_order_contract_type/ir_default.xml',
        'data/work_items/ir_default.xml',
        # server actions
        'data/purchase_cost_update/ir_actions_server.xml',
        'data/remarks/ir_actions_server.xml',
        'data/sale_order_sequencing_and_references/ir_actions_server.xml',
        'data/work_items/ir_actions_server.xml',
        'data/sale_order_delivery_progress_management/ir_actions_server.xml',
        'data/product_cost_nature/ir_actions_server.xml',
        # views/act_windows
        'data/work_items/ir_actions_act_window.xml',
        'data/work_item_lines_procurement/ir_actions_act_window.xml',

        'data/views_standard.xml',
        'data/remarks/ir_ui_view.xml',
        'data/work_items/ir_ui_view.xml',
        'data/work_item_lines_procurement/ir_ui_view.xml',

        'data/remarks/ir_actions_act_window.xml',
        'data/sale_order_delivery_progress_management/ir_actions_act_window.xml',
        # automations
        'data/remarks/base_automation.xml',
        'data/purchase_cost_update/base_automation.xml',
        'data/work_items/base_automation.xml',
        'data/sale_order_sequencing_and_references/base_automation.xml',
        'data/sale_order_delivery_progress_management/base_automation.xml',
        'data/product_cost_nature/base_automation.xml',
        # embedded actions
        'data/remarks/ir_embedded_actions.xml',
        'data/sale_order_delivery_progress_management/ir_embedded_actions.xml',
        'data/work_item_lines_procurement/ir_embedded_actions.xml',
        # menus
        'data/remarks/ir_ui_menu.xml',
        'data/work_items/ir_ui_menu.xml',
        'data/work_item_lines_procurement/ir_ui_menu.xml',

        # records
        'data/ir_model_access.xml',
        'data/project_project.xml',
        'data/x_remark_stage.xml',
        'data/qweb_view.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/x_work_item.xml',
        'data/x_work_item_line.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/x_remark_category.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_project.xml',
        'demo/x_remark_stage.xml',
        'demo/x_remark.xml',
        'demo/sale_order_post.xml',
        'demo/ir_attachment.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'construction_developer/static/src/widgets/apply_to_section_widget.js',
            'construction_developer/static/src/widgets/apply_to_section_widget.xml',
            'construction_developer/static/src/widgets/project_remark_state_selection.js',
            'construction_developer/static/src/scss/sale_order.scss',
            'construction_developer/static/src/js/mail_chatter.xml',
            'construction_developer/static/src/js/patch.js',
        ],
    },
    'cloc_exclude': [
        'data/qweb_view.xml',
        'static/src/scss/sale_order.scss',
        'static/src/widgets/apply_to_section_widget.xml',
        "static/src/js/mail_chatter.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'url': "https://www.odoo.com/trial?industry&selected_app=construction_developer",
    'website': "https://www.odoo.com/all-industries",
}
