{
    'name': 'Construction Developer',
    'version': '1.12',
    'category': 'Construction',
    'depends': [
        'base_industry_data',
        'construction',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',

        'features/product_cost_nature.xml',
        'features/purchase_cost_update_automation.xml',
        'features/remarks.xml',
        'features/sale_order_contract_type.xml',
        'features/sale_order_delivery_progress_management.xml',
        'features/sale_order_sequencing_and_references.xml',
        'features/views_standard.xml',
        'features/work_items.xml',
        'features/work_item_lines_procurement.xml',

        'data/ir_model_access.xml',
        'data/project_project.xml',
        'data/x_remark_stage.xml',
        'data/qweb_view.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/x_work_item.xml',
        'data/x_work_item_line.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/x_remark_category.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_project.xml',
        'demo/x_remark_stage.xml',
        'demo/x_remark.xml',
        'demo/sale_order_post.xml',
        'demo/ir_attachment.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'construction_developer/static/src/widgets/apply_to_section_widget.js',
            'construction_developer/static/src/widgets/apply_to_section_widget.xml',
            'construction_developer/static/src/widgets/project_remark_state_selection.js',
            'construction_developer/static/src/scss/sale_order.scss',
            'construction_developer/static/src/js/mail_chatter.xml',
            'construction_developer/static/src/js/patch.js',
        ],
    },
    'cloc_exclude': [
        'data/qweb_view.xml',
        'static/src/scss/sale_order.scss',
        'static/src/widgets/apply_to_section_widget.xml',
        "static/src/js/mail_chatter.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'url': "https://www.odoo.com/trial?industry&selected_app=construction_developer",
    'website': "https://www.odoo.com/all-industries",
}
