{
    'name': 'Nonprofit organization',
    'version': '2.1',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'documents_project',
        'hr_expense',
        'hr_sign',
        'knowledge',
        'mass_mailing',
        'partnership',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_subscription',
        'survey',
        'web_studio',
        'website_crm',
        'website_event_sale',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/crm_tag.xml',
        'data/crm_stage.xml',
        'data/ir_model_fields.xml',
        'data/account_report.xml',
        'data/account_journal.xml',
        'data/ir_actions_act_window.xml',
        'data/res_partner_category.xml',
        'data/ir_ui_view.xml',
        'data/hr_employee_category.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/qweb_view.xml',
        'data/ir_ui_menu.xml',
        'data/res_config_settings.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/website_menu.xml',
        'data/website_theme_apply.xml',
        'data/mail_template.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/project_task_type.xml',
        'demo/project_project.xml',
        'demo/event_tag.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/hr_job.xml',
        'demo/hr_expense.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/project_tags.xml',
        'demo/project_task.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/survey_survey.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/sale_order_confirm.xml',
        'demo/mailing_mailing.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/qweb_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/qweb_view.xml",
        "data/res_config_settings.xml",
        "demo/qweb_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=non_profit_organization",
    'website': "https://www.odoo.com/industries/nonprofit-organization",
}
