{
    'name': 'Property Listing',
    'version': '1.1',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'sale_crm',
        'web_studio',
        'website_crm',
        'website_sale',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_access.xml',
        'data/ir_model_fields.xml',
        'data/mail_template.xml',
        'data/ir_default.xml',
        'data/ir_actions_server.xml',
        'data/ir_actions_act_window.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/ir_ui_view.xml',
        'data/res_config_settings.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/base_automation.xml',
        'data/crm_team.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
        'data/website_theme_apply.xml',
        'data/uninstall_hook.xml',
        'data/website.xml',
    ],
    'demo': [
        'demo/product_attribute_value.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/website_view.xml',
        'data/uninstall_hook.xml',
    ],
    'images': ['images/main.png'],
}
