{
    'name': 'Booking Engine',
    'version': '1.0',
    'category': 'Hidden/Tools',
    'author': 'Odoo S.A.',
    'depends': [
        'base_automation',
        'contacts',
        'knowledge',
        'sale_project',
        'sale_renting_planning',
        'web_studio',
        'website_appointment',
        'website_sale_renting',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/account_tax.xml',
        'data/product_template.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_menu.xml',
        'data/sale_temporal_recurrence.xml',
        'data/website_view.xml',
        'data/website_menu.xml',
        'data/resource_calendar_data.xml',
        'data/product_category.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
    ],
    'demo': [
        'demo/website_menu.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/website_view.xml',
    ],
}
