{
    'name': 'FMCG Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This module setup a Point of Sale (POS) system for a grocery store which is essential for efficiently managing various product categories, handling transactions, and providing excellent customer service.
""",
    'depends': [
        "account_followup",
        "calendar",
        "hr_hourly_cost",
        "knowledge",
        "pos_hr",
        "pos_sale",
        "pos_discount",
        "loyalty",
        "product_expiry",
        "purchase_product_matrix",
        "purchase_stock",
        "sale_loyalty",
        "sale_product_matrix",
        "sale_purchase",
        "sale_service",
        "stock_delivery",
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/pos_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_config.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_rule.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_post.xml',
    ],
    'license': 'OPL-1',
}
