{
    'name': 'Grocery Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This module setup a Point of Sale (POS) system for a grocery store which is essential for efficiently managing various product categories, handling transactions, and providing excellent customer service.
""",
    'depends': [
        'account_followup',
        'knowledge',
        'loyalty',
        'payment_demo',
        'pos_sale',
        'pos_discount',
        'product_expiry',
        'purchase_stock',
        'sale_purchase',
        'stock_barcode',
        'stock_delivery',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_tag.xml',
        'data/pos_config.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/product_packaging.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_rule.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order_post.xml',
        'demo/pos_payment_method.xml',
        'demo/payment_provider.xml',
        'demo/payment_method.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/pos_confirm.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
