{
    'name': 'Theater',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment',
        'base_industry_data',
        'crm_enterprise',
        'hr_sign',
        'knowledge',
        'partnership',
        'point_of_sale',
        'pos_restaurant',
        'pos_self_order',
        'project',
        'sale_planning',
        'survey',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_mass_mailing',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/res_partner_grade.xml',
    ],
    'demo': [
        'demo/product_product.xml',
        'demo/loyalty_program.xml',
        'demo/hr_employee.xml',
        'demo/website.xml',
        'demo/loyalty_rule.xml',
        'demo/event_event.xml',
        'demo/event_slot.xml',
        'demo/restaurant_floor.xml',
        'demo/restaurant_table.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/pos_session.xml',
        'demo/event_event_ticket.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        # 'demo/website_page.xml',
        # 'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}