{
    'name': 'Theater',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'event_crm',
        'hr_homeworking',
        'hr_sign',
        'hr_skills',
        'knowledge',
        'l10n_be_reports',
        'partnership',
        'pos_event',
        'pos_hr',
        'pos_loyalty',
        'pos_online_payment_self_order',
        'pos_self_order_preparation_display',
        'pos_self_order_sale',
        'sale_crm',
        'sale_loyalty_delivery',
        'sale_pdf_quote_builder',
        'sale_planning',
        'survey',
        'website_appointment_sale_project',
        'website_crm',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_mass_mailing',
        'website_sale_stock',
    ],
    'data': [
        'data/knowledge_article.xml',
        'data/restaurant_floor.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/restaurant_table.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/loyalty_program.xml',
        'demo/hr_employee.xml',
        'demo/website.xml',
        'demo/loyalty_rule.xml',
        'demo/event_event.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/event_event_ticket.xml',
        'demo/loyalty_reward.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}