{
    'name': 'Theater',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'knowledge',
        'partnership',
        'pos_event',
        'pos_self_order',
        'project',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_mass_mailing',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_product.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/res_partner_grade.xml',
        'data/ir_attachment.xml',
        'data/event_event.xml',
        'data/event_slot.xml',
        'data/event_event_ticket.xml',
    ],
    'demo': [
        'demo/product_product.xml',
        'demo/event_event.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=theater",
}
