{
    'name': 'Photography',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'crm',
        'documents_project',
        'knowledge',
        'project_enterprise',
        'sale_management',
        'sale_project',
        'sign',
        'website_appointment',
    ],
    'data': [
        'data/res_groups_data.xml',
        'data/mail_templates.xml',
        'data/project_data.xml',
        'data/product_data.xml',
        'data/appointment_data.xml',
        'data/sale_order_template_data.xml',
        'data/crm_tags_data.xml',
        'data/ir_attachment.xml',
        'data/documents_folder.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/appointment_data.xml',
        'demo/sale_order.xml',
        "demo/sale_order_confirm.xml",
        'demo/project_task.xml',
        'demo/documents_folder.xml',
        'demo/appointment.xml',
        'demo/website_ir_attachment.xml',
        "demo/website.xml",
        'demo/website_view.xml',
        "demo/website_theme_apply.xml",
        'demo/website_page.xml',
        'demo/website_menu.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'photography/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "data/website_view.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
}
