{
    'name': 'Photography',
    'version': '1.2',
    'category': 'Services',
    'depends': [
        'crm',
        'documents_project',
        'knowledge',
        'project_enterprise',
        'sale_management',
        'sale_project',
        'sign',
        'website_appointment',
    ],
    'data': [
        'data/mail_templates.xml',
        'data/project_data.xml',
        'data/product_data.xml',
        'data/appointment_data.xml',
        'data/sale_order_template_data.xml',
        'data/crm_tags_data.xml',
        'data/ir_attachment.xml',
        'data/documents_folder.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/website_view.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        "demo/sale_order_confirm.xml",
        'demo/project_task.xml',
        'demo/documents_folder.xml',
        'demo/appointment.xml',
        'demo/appointment_data.xml',
        'demo/website/website.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/about.xml',
        'demo/website/pages/services.xml',
        'demo/website/pages/portfolio.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/server_actions.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'photography/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "data/website_view.xml",
        'demo/website/pages/home.xml',
        'demo/website/pages/about.xml',
        'demo/website/pages/services.xml',
        'demo/website/pages/portfolio.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/views/website_templates.xml',
        'static/src/scss/primary_variables.scss',
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=photography",
    'website': "https://www.odoo.com/industries/photography",
}
