{
    'name': 'Excise Management',
    'version': '1.0',
    'category': 'Inventory/Inventory',
    'author': 'Odoo S.A.',
    'depends': [
        'account_tax_python',
        'base_automation',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/account_tax_group.xml',
        'data/stock_warehouse.xml',
        'data/uom_uom.xml',
        'data/x_excise_category.xml',
        'data/res_config_setting.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
