{
    'name': 'Environmental Agency',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'base_industry_data',
        'crm_enterprise',
        'documents_project',
        'knowledge',
        'sale_timesheet_enterprise',
        'spreadsheet_sale_management',
        'website_appointment',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/crm_team.xml',
        'data/crm_tag.xml',
        'data/appointment_type.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/project_task_type.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/document_document.xml',
    ],
    'demo': [
        'demo/ir_attachment_post.xml',
        'demo/res_company.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_analytic_line.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=environmental_agency",
    'website': "https://www.odoo.com/industries/environmental-agency",
}
