{
    'name': 'Environmental Agency',
    'version': '1.0',
    'category': 'Services',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'crm_enterprise',
        'documents_project',
        'knowledge',
        'sale_timesheet_enterprise',
        'spreadsheet_sale_management',
        'website_appointment',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/crm_team.xml',
        'data/crm_tag.xml',
        'data/appointment_type.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/website_theme_apply.xml',
        'demo/website_view.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/ir_attachment_post.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'environmental_agency/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
        'static/src/js/my_tour.js',
    ],
    'images': ['images/main.png'],
}
