{
    'name': 'Account firm',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'crm_enterprise',
        'documents_account',
        'documents_hr',
        'documents_product',
        'documents_project',
        'documents_spreadsheet',
        'knowledge',
        'sale_crm',
        'sale_planning',
        'sale_timesheet_enterprise',
        'sign',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/mail_activity_type.xml',
        'data/crm_stage.xml',
        'data/documents_document.xml',
        'data/knowledge_article.xml',
        'data/knowledge_tour.xml',
        'data/knowledge_article_favourite.xml',
        'data/planning_role.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/project_project_stage.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_tags.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/documents_document.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/sale_order_confirm.xml',
        'demo/sale_order_post_action.xml',
        'demo/mail_activity.xml',
        'demo/account_analytic_line.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'accounting_firm/static/src/js/my_tour.js',
        ]
    },
    'cloc_exclude': [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': [
        'images/main.png'
    ],
    'license': 'OPL-1',
}
