{
    'name': 'Account firm',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'accountant',
        'base_industry_data',
        'crm_enterprise',
        'documents',
        'knowledge',
        'project',
        'sale_planning',
        'sale_timesheet_enterprise',
        'sign',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/mail_activity_type.xml',
        'data/crm_stage.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favourite.xml',
        'data/planning_role.xml',
        'data/product_category.xml',
        'data/documents_document.xml',
        'data/project_tags.xml',
        'data/project_project_stage.xml',
        'data/project_task_type.xml',
        'data/project_task_recurrence.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/project_task.xml',
        'data/mail_message.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/mail_activity.xml',
        'demo/account_analytic_line.xml',
        'demo/base_automation.xml',
        'demo/ir_actions_server.xml',
        'demo/sale_order_post_action.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': [
        'images/main.png'
    ],
    'license': 'OPL-1',
}
