{
    'name': 'Nonprofit organization',
    'version': '2.0',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'documents_project',
        'hr_sign',
        'hr_skills_survey',
        'knowledge',
        'mass_mailing',
        'partnership',
        'sale_planning',
        'sale_subscription',
        'web_studio',
        'website_crm',
        'website_event_sale',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/crm_stage.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/mail_template.xml',
        'data/res_partner_category.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/product_category.xml',
        'data/documents_document.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/x_petition_tag.xml',
        'data/x_petition.xml',
        'data/x_signature.xml',
    ],
    'demo': [],
    'author': 'Odoo S.A.',
    'license': 'OPL-1'
}
