{
    'name': 'Nonprofit organization',
    'version': '2.0',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'documents_project',
        'hr_expense',
        'hr_sign',
        'hr_skills_survey',
        'knowledge',
        'mass_mailing',
        'partnership',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_subscription',
        'web_studio',
        'website_crm',
        'website_event_sale',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/crm_stage.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_default.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/mail_template.xml',
        'data/res_partner_category.xml',
        'data/ir_sequence.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/hr_employee_category.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/qweb_view.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/res_config_settings.xml',
        'data/ir_model_access.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/website_page.xml',
        'data/website_controller_page.xml',
        'data/website_menu.xml',
        'data/website_theme_apply.xml',
        'data/x_petition_tag.xml',
        'data/crm_tag.xml',
        'data/website.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/project_task_type.xml',
        'demo/project_project.xml',
        'demo/product_pricelist.xml',
        'demo/product_pricelist_item.xml',
        'demo/x_petition.xml',
        'demo/event_tag.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/hr_job.xml',
        'demo/hr_expense.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/project_tags.xml',
        'demo/project_task.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/survey_survey.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/x_signature.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_payment.xml',
        'demo/mailing_mailing.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/qweb_view.xml",
    ],
    'images': ['images/main.png'],
}
