{
    'name': 'Agricultural Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
    Tailored Setup for Agricultural Retail Businesses:
    This module is for B2B and B2C sales of farming products, including seeds, pesticides, plant nutrition, and equipment. The setup integrates all necessary modules (Point of Sale, Inventory, Sales, Purchase, ...) to run your business with the possibility to expand into online sales with the ecommerce and website applications.
""",
    'depends': [
        'crm',
        'knowledge',
        'pos_sale',
        'product_expiry',
        'purchase_requisition',
        'sale_purchase',
        'survey',
        'web_studio',
        'website_sale_loyalty',
        'theme_enark',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_actions_server.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/product_product.xml',
        'data/product_pricelist_item.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/ir_model_data.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/product_product.xml',
        'demo/survey_survey.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_rule.xml',
        'demo/loyalty_reward.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/loyalty_card.xml',
        'demo/sale_order_post.xml',
        'demo/website.xml',
        'demo/website_views.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website_ir_attachment.xml',
        'demo/payment_provider_demo_post.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'agriculture_shop/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
