{
    'name': 'Sports coach',
    'version': '1.0',
    'category': 'Health & Fitness',
    'description': "",
    'depends': [
        'appointment_account_payment',
        'appointment_crm',
        'appointment_hr',
        'base_vat',
        'calendar',
        'knowledge',
        'sale_crm',
        'sale_timesheet',
        'sale_project',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/crm_stage.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/calendar_event.xml',
        'demo/project_tags.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/account_analytic_line.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'sports_coach/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
}
