{
    'name': 'Marketplace',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'contacts',
        'crm',
        'hr',
        'knowledge',
        'project',
        'purchase',
        'stock',
        'website',
        'website_sale',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/res_config_settings.xml',
        'data/res_config_settings_views.xml',
        'data/products_portal_templates.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/website_view.xml',
        'data/ir_actions_server.xml',
    ],
    'demo': [
        'demo/res_config_settings.xml',
        'demo/product_template.xml',
        'demo/product_product.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
}
