{
    'name': 'Team Sports Club',
    'version': '1.0',
    'category': 'Health & Fitness',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'appointment_hr',
        'base_industry_data',
        'crm_enterprise',
        'event_crm',
        'hr_homeworking',
        'hr_skills',
        'knowledge',
        'pos_event',
        'pos_hr',
        'pos_online_payment_self_order',
        'pos_self_order_preparation_display',
        'pos_self_order_sale',
        'project_enterprise',
        'sale_crm',
        'sale_planning',
        'sale_project_stock',
        'spreadsheet_sale_management',
        'web_studio',
        'website_appointment_sale_project',
        'website_crm_partner_assign',
        'website_event_sale',
        'website_sale_stock',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_menu.xml',
        'data/ir_default.xml',
        'data/appointment_type.xml',
        'data/restaurant_floor.xml',
        'data/pos_config.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/product_attribute.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_project_stage.xml',
        'data/restaurant_table.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/ir_attachment_post.xml',
        'demo/event_event.xml',
        'demo/event_event_ticket.xml',
        'demo/appointment_type.xml',
        'demo/planning_recurrency.xml',
        'demo/calendar_event.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/pos_prep_display.xml',
        'demo/planning_slot.xml',
        'demo/product_template.xml',
        'demo/res_partner_grade.xml',
        'demo/res_partner.xml',
        'demo/res_partner_category.xml',
        'demo/crm_lead.xml',
        'demo/project_task.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website_theme_apply.xml',
        'demo/website_menu.xml',
        'demo/website_view.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'team_sports_club/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
