{
    'name': 'Solar Energy Systems',
    'version': '2.0',
    'category': 'Services',
    'depends': [
        'account_followup',
        'appointment_account_payment',
        'base_industry_data',
        'delivery',
        'documents_project',
        'helpdesk_account',
        'helpdesk_planning_field_service',
        'helpdesk_repair',
        'planning_field_service_sale_stock',
        'planning_field_service_sale_worksheet',
        'product_expiry',
        'project_sms',
        'sale_crm',
        'sale_management',
        'sale_purchase',
        'sign',
        'stock_landed_costs',
        'survey',
        'web_studio',
        'website_crm',
        'website_helpdesk',
        'website_livechat',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_model_access.xml',
        'data/res_config_settings.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/worksheet_template.xml',
        'data/planning_role.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/crm_stage.xml',
        'data/crm_team.xml',
        'data/website_view.xml',
        'data/helpdesk_config.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/res_users.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/account_analytic_plan.xml',
        'demo/account_analytic_account.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_project.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/im_livechat_channel_rule.xml',
        'demo/website_ir_attachment.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/helpdesk_ticket.xml',
        'demo/repair_order.xml',
        'demo/repair_order_confirm.xml',
        'demo/ir_attachment_post.xml',
        'demo/planning_slot.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'solar_installation/static/src/js/sale_order_line_field.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/website_view.xml",
        "static/src/js/sale_order_line_field.js",
        "demo/website_view.xml",
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=solar_installation",
    'website': "https://www.odoo.com/industries/solar-energy",
}
