{
    'name': 'Solar Energy Systems',
    'version': '1.2',
    'category': 'Construction',
    'depends': [
        'account_followup',
        'helpdesk_account',
        'helpdesk_planning_field_service',
        'helpdesk_repair',
        'mrp_account',
        'planning_field_service_sale_stock',
        'planning_field_service_sale_worksheet',
        'product_expiry',
        'project_sms',
        'sale_crm',
        'sale_purchase',
        'stock_landed_costs',
        'web_studio',
        'website_crm',
        'website_helpdesk_knowledge',
        'website_livechat',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/helpdesk_config.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/worksheet_template.xml',
        'data/project_project.xml',
        'data/planning_role.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/crm_stage.xml',
        'data/crm_team.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/account_analytic_plan.xml',
        'demo/account_analytic_account.xml',
        'demo/project_project.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/project_task.xml',
        'demo/project_task_post.xml',
        'demo/im_livechat_channel_rule.xml',
        'demo/website_ir_attachment.xml',
        'demo/helpdesk_ticket.xml',
        'demo/repair_order.xml',
        'demo/repair_order_confirm.xml',
        'demo/ir_attachment_post.xml',
        'demo/planning_slot.xml',
        'demo/website/website.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/get_a_quote.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/product_and_services.xml',
        'demo/website/pages/thanks_contact_us.xml',
        'demo/website/menu.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/server_actions.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'solar_installation/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "static/src/scss/primary_variables.scss",
        "demo/website/views/website_templates.xml",
        "demo/website/pages/get_a_quote.xml",
        "demo/website/pages/home.xml",
        "demo/website/pages/product_and_services.xml",
        "demo/website/pages/thanks_contact_us.xml",
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=solar_installation",
    'website': "https://www.odoo.com/industries/solar-energy",
}
