{
    'name': 'Guided Tours',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'appointment_google_calendar',
        'appointment_hr',
        'base_industry_data',
        'contacts',
        'event_sale',
        'hr_sign',
        'knowledge',
        'pos_enterprise',
        'sale_planning',
        'sale_project',
        'website_appointment',
        'website_event',
        'website_sale_stock',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/appointment_resource.xml',
        'data/uom_uom.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_attribute.xml',
        'data/product_public_category.xml',
        'data/project_project_stage.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/crm_team.xml',
        'demo/hr_employee.xml',
        'demo/website.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/hr_department.xml',
        'demo/account_analytic_plan.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/res_partner.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website_view.xml',
    ],
    'license': 'OPL-1',
    'assets': {
                'web.assets_backend': [
                    'guided_tours/static/src/js/my_tour.js',
                ],
            },
        'cloc_exclude': [
            'data/knowledge_article.xml',
            'static/src/js/my_tour.js',
            'demo/website_view.xml',
        ],
        'images': [
            'images/main.png',
        ],
}