{
    'name': 'Guided Tours',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'appointment_hr',
        'base_industry_data',
        'contacts',
        'event_sale',
        'hr_sign',
        'knowledge',
        'pos_enterprise',
        'sale_planning',
        'sale_project',
        'website_appointment',
        'website_event',
        'website_sale_stock',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/res_config_setting.xml',
        'data/appointment_resource.xml',
        'data/pos_category.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/event_event.xml',
        'data/event_slot.xml',
        'data/event_event_ticket.xml',
        'data/event_stage.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_public_category.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/event_stage.xml',
        'demo/appointment_type.xml',
        'demo/event_event.xml',
        'demo/product_product.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/ir_attachment_post.xml',
        'demo/res_partner.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
