{
    'name': 'IT Hardware Sales and Support',
    'version': '1.0',
    'category': 'Services',
    'description': """
We offer IT sales, installation, and repair services for a wide range of products, including laptops, RAM, accessories, and CCTV cameras.
""",
    'depends': [
        'account_followup',
        'appointment_crm',
        'helpdesk',
        'helpdesk_repair',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'payment_demo',
        'product_expiry',
        'purchase_stock',
        'sale_crm',
        'sale_purchase',
        'stock_barcode',
        'website_appointment',
        'website_crm',
        'website_helpdesk_knowledge',
        'website_sale_comparison',
        'website_sale_stock',
        'theme_graphene',
    ],
    'data': [
        'data/helpdesk_config.xml',
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/stock_picking_type.xml',
        'data/ir_ui_view.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/project_project.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/payment_provider_demo.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_lot.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_location.xml',
        'demo/helpdesk_ticket.xml',
        'demo/repair_order.xml',
        'demo/repair_order_confirm.xml',
        'demo/website_attachment.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
    'maintenance_loc': 0,
}
