{
    'name': 'Museum',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'calendar',
        'documents_sign',
        'hr',
        'knowledge',
        'partnership',
        'pos_event',
        'purchase_stock',
        'sale_planning',
        'sale_subscription',
        'website_event_sale',
    ],
    'data': [
        'data/product_pricelist.xml',
        'data/res_config_settings.xml',
        'data/ir_default.xml',
        'data/ir_attachment_pre.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_pricelist_item.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_public_category.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
        'data/res_partner_category.xml',
        'data/hr_job.xml',
    ],
    'demo': [
        'demo/event_event.xml',
        'demo/event_question.xml',
        'demo/event_slot.xml',
        'demo/event_event_ticket.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/planning_recurrency.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/sign_request.xml',
        'demo/stock_location.xml',
        'demo/product_product.xml',
        'demo/account_move.xml',
        'demo/account_move_line.xml',
        'demo/res_partner_category.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/planning_slot_template.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'museum/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=museum",
    'website': "https://www.odoo.com/all-industries",
}
