{
    'name': 'Museum',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'calendar',
        'documents_sign',
        'hr',
        'knowledge',
        'partnership',
        'pos_event',
        'purchase_stock',
        'sale_planning',
        'sale_subscription',
        'website_event_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_default.xml',
        'data/ir_attachment_pre.xml',
        'data/documents_document.xml',
        'data/event_event.xml',
        'data/event_question.xml',
        'data/event_slot.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_product.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_pricelist_item.xml',
        'data/product_public_category.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_item.xml',
        # 'data/sign_request_item.xml',
        # 'data/sign_request.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/res_partner_category.xml',
        'data/stock_location.xml',
        'data/hr_job.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/documents_document.xml',
        'demo/event_event.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/planning_recurrency.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/product_product.xml',
        'demo/account_move.xml',
        'demo/account_move_line.xml',
        'demo/res_partner_category.xml',
        'demo/purchase_order.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/purchase_order_line.xml',
        'demo/planning_slot_template.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_quant.xml',
        'demo/website.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/website_view.xml',
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
