{
    'name': 'Hotel',
    'version': '1.4',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'account_pos_settle_due',
        'base_industry_data',
        'booking_engine',
        'pos_restaurant',
        'web_studio',
    ],
    'data': [
        'data/pos_config.xml',
        'data/product_template.xml',
        'data/resource_resource.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_image.xml',
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/views.xml',
        'data/product_pricing.xml',
    ],
    'demo': [
        'demo/hr_employee.xml',
        'demo/product_template_post.xml',
        'demo/pos_config.xml',
        'demo/product_attribute.xml',
        'demo/rating_rating.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=hotel",
    'website': "https://www.odoo.com/industries/hotel",
}
