{
    'name': 'Members Club',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'crm_sale_subscription',
        'event_crm',
        'knowledge',
        'marketing_automation',
        'partnership',
        'project_sale_subscription',
        'website_blog',
        'website_event_sale',
        'website_sale_subscription',
    ],
    'data': [
        'data/res_config_setting.xml',
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/product_public_category.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/product_pricelist_item.xml',
        'data/knowledge_article_favorite.xml',
        'data/blog_blog.xml',
        'data/blog_tag.xml',
        'data/mailing_filter.xml',
        'data/mailing_mailing.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/website_view.xml',
        'demo/blog_post.xml',
        'demo/event_event.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=members_club",
    'website': "https://www.odoo.com/all-industries",
}
