{
    'name': 'Members Club',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'crm_sale_subscription',
        'event_crm',
        'hr_homeworking',
        'knowledge',
        'partnership',
        'project_sale_subscription',
        'survey',
        'website_blog',
        'website_event_sale',
        'website_sale_subscription',
    ],
    'data': [
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/product_public_category.xml',
        'data/sale_subscription_pricing.xml',
        'data/product_product.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/knowledge_article_favorite.xml',
        'data/blog_blog.xml',
        'data/blog_tag.xml',
    ],
    'demo': [
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/blog_post.xml',
        'demo/event_event.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
    ],
    'license': 'OPL-1',
        'cloc_exclude': [
            'data/knowledge_article.xml',
            'static/src/js/my_tour.js',
            'demo/website_view.xml',
        ],
        'images': [
            'images/main.png',
        ],
}
