{
    'name': 'Sports Facilities',
    'version': '1.3',
    'category': 'Health and Fitness',
    'depends': [
        'appointment_crm',
        'knowledge',
        'partnership',
        'planning',
        'pos_restaurant',
        'sale_subscription',
        'website_appointment',
        'website_crm',
        'website_sale_collect',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/pos_category.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/ir_attachment_pre.xml',
        'data/product_public_category.xml',
        'data/planning_role.xml',
        'data/product_pricelist.xml',
        'data/res_partner_grade.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/resource_calendar.xml',
        'data/appointment_resource.xml',
        'data/appointment_type.xml',
        'data/knowledge_tour.xml',
        'data/product_pricelist_item.xml',
        'data/account_tax.xml'
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/product_template.xml',
        'demo/product_product.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/planning_slot.xml',
        'demo/mail_message.xml',
        'demo/appointment_invite.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/website_ir_attachments.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
    'assets': {
        'web.assets_backend': [
            'sports_facilities/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        'demo/website_view.xml',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=sports_facilities",
    'website': "https://www.odoo.com/industries/sports-club",
}
