{
    'name': 'Machine Tool Rental',
    'version': '1.0',
    'category': 'Construction',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'industry_fsm_sale_report',
        'knowledge',
        'purchase',
        'quality_control',
        'sale_crm',
        'sale_stock_renting',
        'web_studio',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        # 'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/product_pricing.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/stock_location.xml',
        'data/quality_point.xml',
        'data/x_maintenance_rules.xml',
        'data/x_run_time_meter.xml',
        'data/mail_message.xml',
        # 'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/stock_lot.xml',
        'demo/x_run_time_meter.xml',
        'demo/stock_quant.xml',
        'demo/stock_move_line.xml',
        'demo/stock_rule.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/quality_check.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/ir_actions_server.xml',
    ],
    'images': ['images/main.png'],
}
