{
    'name': 'Elearning Platform',
    'version': '1.0',
    'category': 'Service',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'hr',
        'knowledge',
        'spreadsheet_sale_management',
        'website_forum',
        'website_sale_mass_mailing',
        'website_sale_slides',
        'website_slides_survey',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist_item.xml',
        'data/product_product.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/website_view.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
}
