{
    'name': 'eLearning Platform',
    'category': 'Service',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'knowledge',
        'mass_mailing',
        'sale_management',
        'website_forum',
        'website_sale_slides',
        'website_slides_survey',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_template.xml',
        'data/product_tag.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist_item.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/res_partner.xml',
        'demo/website_view.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/survey_survey.xml',
        'demo/slide_channel_tag_group.xml',
        'demo/slide_channel_tag.xml',
        'demo/slide_channel.xml',
        'demo/slide_tag.xml',
        'demo/slide_slide.xml',
        'demo/survey_question.xml',
        'demo/survey_question_answer.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=elearning_platform",
    'website': "https://www.odoo.com/all-industries",
}
