{
    'name': 'Microbrewery',
    'version': '2.0',
    'category': 'Supply Chain',
    'depends': [
        'account',
        'appointment_crm',
        'base_automation',
        'base_industry_data',
        'excise_management',
        'knowledge',
        'mrp_subcontracting',
        'pos_restaurant',
        'pos_sale',
        'sale_purchase',
        'sale_renting',
        'web_studio',
        'website_appointment',
        'website_project',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/website_base_unit.xml',
        'data/account_tax.xml',
        'data/x_excise_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_pricing.xml',
        'data/product_product.xml',
        'data/mrp_bom_byproduct.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/product_template_post.xml',
        'data/mrp_workcenter.xml',
        'data/mrp_routing_workcenter.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/quality_point.xml',
        'data/appointment_type.xml',
        'data/website_view.xml',
        'data/sale_order_spreadsheet.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/mrp_bom.xml',
        'demo/crm_lead.xml',
        'demo/appointment_type.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_template.xml',
        'demo/stock_lot.xml',
        'demo/stock_quant.xml',
        'demo/stock_warehouse.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/mrp_orderpoint_post.xml',
        'demo/mrp_production.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_picking.xml',
        'demo/website_attachment.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/website_view.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=micro_brewery",
}
