{
    'name': 'Custom Website Armadale',
    'description': 'A professional Odoo theme for textile manufacturing businesses',
    'version': '19.0.1.0.0',
    'author': 'Odoo',
    'license': 'LGPL-3',
    'depends': [
        'website',
        'website_blog',
        'website_sale',
        'delivery',
    ],
    'data': [
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/ir_attachment_business.xml',
        'data/blog_blog.xml',
        'data/blog_post.xml',
    ],
    'demo': [
        'demo/website/website.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/about_us.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/home.xml',
        'demo/website/menu.xml',
        'demo/website/server_actions.xml',
    ],
}
