{
    'name': 'Textile Manufacturing',
    'version': '1.7',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'documents_project',
        'hr_timesheet',
        'mrp_subcontracting',
        'product_conversion',
        'purchase_mrp',
        'quality_mrp_workorder',
        'sale_project',
        'website_blog',
        'website_crm',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_ui_menu.xml',
        'data/ir_attachment_pre.xml',
        'data/documents_document.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_product.xml',
        'data/project_task_type.xml',
        'data/project_project_stage.xml',
        'data/project_project.xml',
        'data/project_tags.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/ir_attachment_post.xml',
        'demo/res_company.xml',
        'demo/documents_document.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/knowledge_article.xml',
        'demo/knowledge_article_favorite.xml',
        'demo/project_project.xml',
        'demo/product_supplierinfo.xml',
        'demo/mrp_bom.xml',
        'demo/mrp_bom_line.xml',
        'demo/mrp_workcenter.xml',
        'demo/mrp_routing_workcenter.xml',
        'demo/stock_lot.xml',
        'demo/mrp_production.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/sale_order.xml',
        'demo/project_task.xml',
        'demo/mail_activity.xml',
        'demo/sale_order_line.xml',
        'demo/stock_picking.xml',
        'demo/stock_move.xml',
        'demo/stock_quant.xml',
        'demo/hr_employee.xml',
        'demo/account_analytic_line.xml',
        'demo/quality_point.xml',
        'demo/sale_order_confirm.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/payment_provider_demo.xml',
        'demo/blog_blog.xml',
        'demo/blog_post.xml',
        'demo/website/website.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/pages/about_us.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/home.xml',
        'demo/website/menu.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/server_actions.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'application': True,
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=textile_manufacturing",
    'website': "https://www.odoo.com/industries/textile-manufacturing",
}
