{
    'name': 'Architecture Firm',
<<<<<<< 870542a7109864cd9d3beb0bfafb9a9937f1ec2a
    'version': '1.2',
    'category': 'Services',
||||||| e5a1ba433a012ad0dcff740c631f8f97783d2861
    'version': '1.0',
    'category': 'Services',
    'description': """
This industry is made for Architecture Firm that sell all kind of architectural services such as feasibility studies,
schematic design, design development, worksite follow-up, energy efficiency assessment.
""",
=======
    'version': '1.0',
    'category': 'Real Estate, Construction and Maintenance',
    'description': """
This industry is made for Architecture Firm that sell all kind of architectural services such as feasibility studies,
schematic design, design development, worksite follow-up, energy efficiency assessment.
""",
>>>>>>> 20014fd4a7f3eef3b4149c7cb00d24f3495f074a
    'depends': [
        'account_followup',
        'base_automation',
        'base_geolocalize',
        'base_industry_data',
        'crm_enterprise',
        'documents_hr',
        'documents_project_sale',
        'documents_spreadsheet',
        'knowledge',
        'sale_crm',
        'sale_expense',
        'sale_planning',
        'timesheet_grid',
        'web_studio',
        'website_appointment',
        'website_crm',
        'website_partner',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/project_task_type.xml',
        'data/documents_document.xml',
        'data/project_project.xml',
        'data/planning_role.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/appointment_type.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/knowledge_tour.xml',
        'data/uninstall_hook.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/hr_expense.xml',
        'demo/hr_expense_action.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'architects/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/uninstall_hook.xml",
        "static/src/js/my_tour.js",
        "data/website_view.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=architects",
    'website': "https://www.odoo.com/industries/architecture-firm",
}
