{
    'name': 'Architects',
    'version': '1.0',
    'category': 'Services',
    'description': """
This industry is made for architects that sell all kind of architectural services such as feasibility studies,
schematic design, design development, worksite follow-up, energy efficiency assessment.
""",
    'author': 'Odoo S.A.',
    'depends': [
        'account_followup',
        'crm_enterprise',
        'documents_hr',
        'documents_product',
        'documents_project_sale',
        'documents_spreadsheet',
        'iap_extract',
        'knowledge',
        'project_sms',
        'sale_crm',
        'sale_expense',
        'sale_planning',
        'timesheet_grid',
        'website_crm',
        'website_partner',
        'theme_real_estate',
        'base_geolocalize',
    ],
    'data': [
        # 'data/res_config_setting.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        # 'data/ir_actions_act_window_view.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        # 'data/knowledge_article_member.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/res_partner.xml',
        'demo/crm_stage.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_views.xml',
        'demo/website_theme_apply.xml',
        'demo/hr_expense.xml',
        'demo/hr_expense_action.xml',
        # 'demo/hr_expense_sheet.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
