{
    'name': 'Custom Furniture Production',
    'version': '1.1',
    'category': 'Supply Chain',
    'depends': [
        'account_followup',
        'calendar',
        'crm',
        'hr',
        'industry_fsm_report',
        'knowledge',
        'mrp_workorder',
        'planning',
        'product_barcodelookup',
        'purchase_stock',
        'quality_control',
        'quality_mrp',
        'sale_project',
        'sale_stock',
        'sale_timesheet',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_ui_menu.xml',
        'data/ir_attachment_pre.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/planning_role.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/mrp_bom_byproduct.xml',
        'data/mrp_workcenter.xml',
        'data/mrp_routing_workcenter.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/quotation_document.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/quality_point.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_users.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_product.xml',
        'demo/stock_quant.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/mrp_production.xml',
        'demo/mrp_workorder.xml',
        'demo/stock_move.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/quality_check.xml',
        'demo/planning_slot.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'custom_furniture/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'license': 'OEEL-1',
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=custom_furniture",
    'website': "https://www.odoo.com/industries/custom-furniture-production",
}
