{
    'name': 'HVAC Services',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'appointment_account_payment',
        'base_industry_data',
        'contacts',
        'hr',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'project_purchase',
        'project_sale_subscription',
        'sale_management',
        'sale_planning',
        'sale_purchase_stock',
        'sale_subscription',
        'web_studio',
    ],
    'data': [
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/product_category.xml',
        'data/hr_job.xml',
        'data/ir_models.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/res_config_settings.xml',
        'data/sale_order_template.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_view.xml',
        'data/qweb_view.xml',
        'data/ir_ui_menu.xml',
        'data/worksheet_template.xml',
        'data/project_project.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/sale_order_template_line.xml',
        'data/base_automation.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_users.xml',
        'demo/hr_employee.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/stock_lot.xml',
        'demo/sale_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/project_task.xml',
        'demo/sale_order_post.xml',
        'demo/x_project_task_worksheet_template.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/qweb_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=hvac_services",
    'website': "https://www.odoo.com/industries/hvac-services",
}
