{
    'name': 'Summer Camps',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'appointment_google_calendar',
        'base_industry_data',
        'crm_enterprise',
        'event_crm',
        'knowledge',
        'sale_crm',
        'sale_planning',
        'sale_project',
        'sign',
        'survey',
        'website_crm',
        'website_event_sale',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/appointment_slot.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/event_type.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_attribute.xml',
        'data/product_public_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/sign_template.xml',
        'data/sign_document.xml',
        'data/mail_message.xml',
        'data/mail_template.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
    ],
    'demo': [
        'demo/hr_department.xml',
        'demo/crm_tag.xml',
        'demo/hr_employee.xml',
        'demo/res_partner.xml',
        'demo/account_analytic_plan.xml',
        'demo/crm_lead.xml',
        'demo/crm_team.xml',
        'demo/appointment_type.xml',
        'demo/appointment_slot.xml',
        'demo/project_task.xml',
        'demo/event_question.xml',
        'demo/event_question_answer.xml',
        'demo/event_event.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/sign_request.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        "data/website_view.xml",
    ],
    'images': [
        'images/main.png',
    ],
}
