{
    'name': 'Summer Camps',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account_followup',
        'appointment_crm',
        'appointment_google_calendar',
        'appointment_hr',
        'base_industry_data',
        'crm_enterprise',
        'event_crm',
        'hr_homeworking',
        'hr_sign',
        'hr_skills',
        'knowledge',
        'project_enterprise',
        'sale_crm',
        'sale_pdf_quote_builder',
        'sale_planning',
        'survey',
        'website_appointment_sale_project',
        'website_crm',
        'website_event_sale',
        'website_product_barcodelookup',
        'website_sale_dashboard',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/appointment_slot.xml',
        'data/crm_stage.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/event_tag_category.xml',
        'data/event_tag.xml',
        'data/event_type.xml',
        'data/event_event.xml',
        'data/event_question.xml',
        'data/event_question_answer.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_attribute.xml',
        'data/product_public_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_project_stage.xml',
        'data/sign_template.xml',
        'data/sign_document.xml',
        'data/sign_request.xml',
        'data/mail_message.xml',
        'data/mail_template.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
        'data/website.xml',
    ],
    'demo': [
        'demo/hr_department.xml',
        'demo/crm_tag.xml',
        'demo/hr_employee.xml',
        'demo/res_partner.xml',
        'demo/account_analytic_plan.xml',
        'demo/crm_lead.xml',
        'demo/crm_team.xml',
        'demo/appointment_type.xml',
        'demo/appointment_slot.xml',
        'demo/project_task.xml',
        'demo/event_event.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'summer_camps/static/src/js/my_tour.js',
        ],
    },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        "data/website_view.xml",
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
}
