{
    'name': 'Custom Industrial Equipment',
    'category': 'Supply Chain',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'documents',
        'hr_timesheet',
        'mrp_plm',
        'planning_field_service_worksheet',
        'project_forecast',
        'purchase',
        'quality_control',
        'repair',
        'website_crm',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/resource_resource.xml',
        'data/mrp_workcenter.xml',
        'data/project_project_stage.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_task.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/crm_tag.xml',
        'demo/knowledge_article.xml',
        'demo/knowledge_article_update.xml',
        'demo/knowledge_article_favorite.xml',
        'demo/res_partner.xml',
        'demo/res_company.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/crm_lead.xml',
        'demo/project_project.xml',
        'demo/project_task.xml',
        'demo/mrp_bom.xml',
        'demo/documents_document.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/mrp_production.xml',
        'demo/mrp_routing_workcenter.xml',
        'demo/quality_point.xml',
        'demo/mrp_workorder.xml',
        'demo/planning_slot.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/stock_lot.xml',
        'demo/sale_order_confirm.xml',
        'demo/repair_order.xml',
        'demo/stock_move.xml',
        'demo/repair_order_confirm.xml',
        'demo/mrp_eco.xml',
        'demo/account_analytic_account.xml',
        'demo/account_analytic_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'version': '1.1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'application': True,
    'url': "https://www.odoo.com/trial?industry&selected_app=custom_industrial_equipment",
    'website': "https://www.odoo.com/all-industries",
}
