{
    'name': 'Driving School',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'contacts',
        'hr_fleet',
        'knowledge',
        'sale_management',
        'sign',
        'website_appointment',
        'website_sale_loyalty',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/uom_uom.xml',
        'data/product_ribbon.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_product.xml',
        'data/appointment_resource.xml',
        'data/appointment_type.xml',
        'data/mail_template.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_item.xml',
        'data/fleet_vehicle_model.xml',
        'data/fleet_vehicle.xml',
        'data/fleet_vehicle_log_services.xml',
        'data/hr_job.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/loyalty_program.xml',
        'demo/fleet_vehicle_log_services.xml',
        'demo/product_template.xml',
        'demo/website_view.xml',
        'demo/res_users.xml',
        'demo/appointment_type.xml',
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/loyalty_reward.xml',
        'demo/loyalty_rule.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=driving_school",
}
