{
    'name': 'Driving School',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_hr',
        'base_automation',
        'base_industry_data',
        'hr_fleet',
        'knowledge',
        'sale_management',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sign',
        'web_studio',
        'website_appointment',
        'website_sale_loyalty',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_product.xml',
        'data/appointment_resource.xml',
        'data/appointment_type.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/crm_team.xml',
        'demo/loyalty_program.xml',
        'demo/hr_job.xml',
        'demo/product_template.xml',
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/hr_department.xml',
        'demo/account_analytic_plan.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/loyalty_reward.xml',
        'demo/res_partner.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/loyalty_rule.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'images': [
        'images/main.png',
    ],
}