{
    'name': 'Wine Merchant',
    'version': '1.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'crm_enterprise',
        'event_crm',
        'hr_calendar',
        'hr_skills',
        'knowledge',
        'pos_enterprise',
        'pos_event',
        'pos_loyalty',
        'pos_online_payment',
        'sale_crm',
        'sale_loyalty_delivery',
        'sale_pdf_quote_builder',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'website_crm',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_stock',
    ],
    'data': [
        'data/crm_stage.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_article.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/crm_team.xml',
        'demo/loyalty_program.xml',
        'demo/website.xml',
        'demo/loyalty_rule.xml',
        'demo/website_view.xml',
        'demo/account_analytic_plan.xml',
        'demo/hr_department.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/pos_order.xml',
        'demo/loyalty_reward.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/stock_quant.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
    ],
    'license': 'OPL-1',
    'assets': {
            'web.assets_backend': [
                'wine_merchant/static/src/js/my_tour.js',
            ],
        },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}