{
    'name': 'Wine Shop',
    'version': '1.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'hr',
        'knowledge',
        'pos_event',
        'pos_loyalty',
        'pos_online_payment',
        'sale_crm',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'website_crm',
        'website_event_sale',
        'website_sale_loyalty',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/ir_attachment.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/loyalty_program.xml',
        'demo/event_event.xml',
        'demo/product_template.xml',
        'demo/loyalty_rule.xml',
        'demo/website_view.xml',
        'demo/hr_department.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/pos_order.xml',
        'demo/loyalty_reward.xml',
        'demo/pos_order_line.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/stock_quant.xml',
        'demo/mail_activity.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
