{
    'name': '3PL Logistic',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'base_industry_data',
        'knowledge',
        'product_expiry',
        'purchase',
        'sale_management',
        'sale_subscription',
        'stock',
        'web_studio',
        'website',
    ],
    'data': [
        'data/knowledge_article.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/portal_templates.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/ir_cron.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/stock_quant.xml',
        'demo/res_users.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/portal_templates.xml',
        'data/ir_cron.xml',
    ],
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
}
