{
    'name': 'Marketing Agency',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'contacts',
        'crm_sale_subscription',
        'event_crm',
        'event_sale',
        'hr',
        'knowledge',
        'planning',
        'project_forecast',
        'project_sale_subscription',
        'sale_timesheet_enterprise',
        'social',
        'spreadsheet_sale_management',
        'website_appointment',
        'website_event',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/uom_uom.xml',
        'data/project_task_type.xml',
        'data/project_tags.xml',
        'data/project_project_stage.xml',
        'data/product_category.xml',
        'data/planning_role.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/event_tag.xml',
        'data/event_event.xml',
        'data/event_event_ticket.xml',
        'data/ir_attachment.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/crm_tag.xml',
        'data/hr_department.xml',
        'data/install_apps.xml',
    ],
    'demo': [
        'demo/crm_team.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/event_event.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/project_project.xml',
        'demo/project_tags.xml',
        'demo/res_partner_category.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_confirm.xml',
        'demo/account_analytic_line.xml',
        'demo/mail_activity.xml',
        'demo/planning_slot.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=marketing_agency",
    'website': "https://www.odoo.com/industries/marketing-agency",
}
