{
    'name': 'Guest House',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'account_tax_python',
        'appointment_account_payment',
        'base_automation',
        'base_industry_data',
        'contacts',
        'knowledge',
        'sale_project',
        'sale_renting_planning',
        'web_studio',
        'website_appointment',
        'website_sale_stock',
        'website_sale_stock_renting',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model_fields.xml',
        'data/planning_role.xml',
        'data/resource_calendar_data.xml',
        'data/resource_resource.xml',
        'data/uom_uom.xml',
        'data/account_tax.xml',
        'data/product_category.xml',   
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/knowledge_tour.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_filters.xml',
        'data/ir_ui_menu.xml',
        'data/sale_temporal_recurrence.xml',
    ],
    'demo': [
        'demo/product_template.xml',
        'demo/product_image.xml',
        'demo/product_product.xml',
        'demo/product_template_attribute_line.xml',
        'demo/product_template_attribute_value.xml',
        'demo/product_pricing.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
        'demo/product_template_post.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}