{
    'name': 'Guest House',
    'version': '1.7',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'booking_engine',
        'web_studio',
    ],
    'data': [
        'data/product_template.xml',
        'data/resource_resource.xml',
        'data/product_product.xml',
        'data/product_template_attribute_line.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/ir_ui_menu.xml',
        'data/ir_ui_view.xml',
        'data/website_view.xml',
        'data/res_config_settings.xml',
        'data/spreadsheet_dashboard.xml',
    ],
    'demo': [
        'demo/res_company.xml',
        'demo/product_template_post.xml',
        'demo/rating_rating.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_post.xml',
        'demo/planning_slot_post.xml',
        'demo/website/website.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/views/website_sale_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/about_us.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/server_actions.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/views/website_sale_templates.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/about_us.xml',
        'demo/website/pages/contactus.xml',
        'static/src/scss/primary_variables.scss',
    ],
    'application': True,
    'images': [
        'images/main.png',
    ],
    'url': "https://www.odoo.com/trial?industry&selected_app=guest_house",
    'website': "https://www.odoo.com/industries/guest-house",
}
