{
    'name': 'Electricians',
    'version': '1.0',
    'category': 'Services',
    'description': '',
    'depends': [
        'account_online_synchronization',
        'account_peppol',
        'appointment',
        'crm_enterprise',
        'industry_fsm_sale',
        'knowledge',
        'planning',
        'project_forecast',
        'purchase',
        'sale_margin',
        'sale_timesheet',
        'sign',
        'stock',
        'survey',
        'web_studio',
        'worksheet'
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/planning_role.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/res_config_settings.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_users.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/product_supplierinfo.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/stock_quant.xml',
        'demo/project_project.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'electrician/static/src/js/my_tour.js',
        ]
        },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
