{
    'name': 'Electricians',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'appointment',
        'base_industry_data',
        'crm_enterprise',
        'industry_fsm_sale',
        'knowledge',
        'planning',
        'project_forecast',
        'purchase',
        'sale_margin',
        'stock',
        'web_studio'
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/crm_tag.xml',
        'data/planning_role.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/res_config_settings.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/product_supplierinfo.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/stock_quant.xml',
    ],
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=electrician",
    'website': "https://www.odoo.com/all-industries",
}
