{
    'name': 'Thrift Store',
    'version': '1.0',
    'category': 'Retail',
    'depends': [
        'base_industry_data',
        'hr',
        'knowledge',
        'planning',
        'pos_online_payment',
        'project',
        'stock',
    ],
    'data': [
        'data/ir_attachment.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/pos_category.xml',
        'data/pos_config.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/planning_role.xml',
        'demo/hr_employee.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/planning_slot_post.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/pos_confirm.xml',
        'demo/pos_config.xml',
        'demo/resource_calendar.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=thrift_store",
    'website': "https://www.odoo.com/all-industries",
}
