{
    'name': 'Takeaway Restaurant',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'knowledge',
        'pos_enterprise',
        'pos_online_payment_self_order',
        'pos_restaurant',
        'purchase_stock',
        'website',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_combo.xml',
        'data/product_template.xml',
        'data/product_tag.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/product_combo_item.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/pos_prep_display.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/product_supplierinfo.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=takeaway_restaurant",
    'website': "https://www.odoo.com/all-industries",
}
