{
    'name': 'Garage',
    'version': '1.0',
    'category': 'Services',
    'depends': [
        'appointment',
        'base_industry_data',
        'calendar',
        'contacts',
        'hr_fleet',
        'knowledge',
        'sale_project',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_default.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/project_task_type.xml',
        'data/fleet_vehicle_state.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/qweb_view.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'cloc_exclude': [
        'data/knowledge_article.xml',
        "data/qweb_view.xml",
    ],
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=garage",
    'website': "https://www.odoo.com/all-industries",
}
