{
    'name': 'Restaurant (Foods & Cafes)',
    'version': '1.0',
    'category': 'Services',
    'description': """
    """,
    'depends': [
        'account_followup',
        'knowledge',
        'calendar',
        'contacts',
        'pos_enterprise',
        'pos_restaurant',
        'purchase_stock',
        'planning',
        'hr_employee',
        'pos_loyalty',
        'pos_online_payment_self_order',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_payment_method.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/ir_model_data.xml',
    ],
    'demo': [
        'demo/pos_payment_method.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/res_config_settings.xml',
        'demo/loyalty_program.xml',
        'demo/kitchen_display.xml',
        'demo/product_packaging.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/planning_role.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_product.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/planning_slot.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
