{
    'name': 'Fast Food',
    'version': '1.0',
    'category': 'Hospitality',
    'depends': [
        'account_followup',
        'calendar',
        'contacts',
        'hr',
        'knowledge',
        'planning',
        'pos_enterprise',
        'pos_loyalty',
        'pos_online_payment_self_order',
        'pos_restaurant',
        'purchase_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_payment_method.xml',
        'data/product_category.xml',
        'data/uom_uom.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/pos_payment_method.xml',
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/res_config_settings.xml',
        'demo/loyalty_program.xml',
        'demo/kitchen_display.xml',
        'demo/stock_quant.xml',
        'demo/stock_warehouse_orderpoint.xml',
        'demo/planning_role.xml',
        'demo/product_supplierinfo.xml',
        'demo/product_product.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/planning_slot.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'fast_food/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
}
