{
    'name': 'Bowling Alley',
    'version': '1.0',
    'category': 'Hospitality',
    'depends': [
        'base_industry_data',
        'knowledge',
        'planning',
        'pos_enterprise',
        'pos_restaurant',
        'website_appointment',
    ],
    'data': [
        'data/appointment_resource.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/appointment_type.xml',
        'data/restaurant_floor.xml',
        'data/restaurant_table.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
    ],
    'demo': [
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=bowling",
    'website': "https://www.odoo.com/all-industries",
}
