{
    'name': 'Bowling Alleys',
    'version': '1.0',
    'category': 'Hospitality',
    'depends': [
        'knowledge',
        'planning',
        'pos_self_order_preparation_display',
        'website_appointment',
    ],
    'data': [
        # 'data/ir_attachment_pre.xml',
        'data/appointment_resource.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/restaurant_floor.xml',
        'data/pos_payment_method.xml',
        'data/restaurant_table.xml',
        # 'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/website.xml',
        'demo/website_view.xml',
        'demo/website_theme_apply.xml',
        'demo/res_partner.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/appointment_resource.xml',
        'demo/ir_attachment_post.xml',
        'demo/pos_config.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'bowling/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
}
