# -*- coding: utf-8 -*-
{
    'name': 'HeadHunter',
    'version': '1.0',
    'category': 'Services',
    'description': """
This setup is for Talent Acquisition Agency / Recruitment Agency / Staffing Agency. Those agencies work on two levels and with two different audiences, ...
""",
    'depends': [
        'account_accountant',
        'appointment_crm',
        'appointment_hr',
        'appointment_hr_recruitment',
        'appointment_sms',
        'base_automation',
        'crm_enterprise',
        'documents_hr_recruitment',
        'documents_product',
        'documents_spreadsheet',
        'hr_hourly_cost',
        'hr_recruitment_skills',
        'knowledge',
        'sign',
        'sale_crm',
        'sale_product_configurator',
        'sale_service',
        'survey',
        'website_appointment',
        'website_crm',
        'website_hr_recruitment'
    ],
    'data': [
        'data/base_automation.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_model_access.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_article.xml',
        'data/survey_survey.xml',
        'data/survey_question.xml',
        'data/survey_question_answer.xml',
        'data/hr_recruitment_stage.xml',
        'data/utm_source.xml',
        'data/appointment_type.xml',
        'data/hr_department.xml',
        'data/hr_job.xml',
        'data/appointment_slot.xml',
        'data/ir_attachment_post.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/website.xml',
        'demo/crm_tag.xml',
        'demo/crm_stage.xml',
        'demo/crm_lead.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/website_ir_attachment.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/hr_applicant.xml',
    ],
    'license': 'OPL-1',
    'images': ['images/main.png'],
}
