{
    'name': 'Furniture Store',
    'version': '1.1',
    'category': 'Retail',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'knowledge',
        'pos_discount',
        'pos_enterprise',
        'pos_online_payment',
        'pos_sale',
        'product_barcodelookup',
        'purchase_stock',
        'sale_crm',
        'sale_purchase',
        'stock_barcode',
        'website_crm',
        'website_sale_collect',
        'website_sale_stock_wishlist',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_public_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/pos_prep_display.xml',
        'data/pos_note.xml',
        'data/product_image.xml',
        'data/res_config_settings.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/delivery_carrier.xml',
        'demo/ir_attachment_post.xml',
        'demo/product_template.xml',
        'demo/website_theme_apply.xml',
        'demo/website_view.xml',
        'demo/crm_tag.xml',
        'demo/crm_lead.xml',
        'demo/pos_session.xml',
        'demo/pos_order.xml',
        'demo/pos_note.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/pos_order_line.xml',
        'demo/stock_quant.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/website.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=furniture_store",
    'website': "https://www.odoo.com/industries/furniture-store",
}
