{
    'name': 'Furniture Store',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This module setup a furniture store for selling furniture like chairs, sofas, dinning tables,
beds, cupboards etc.
""",
    'author': 'Odoo S.A.',
    'depends': [
        'account_check_printing',
        'knowledge',
        'mrp',
        'pos_sale',
        'sale_margin',
        'sale_planning',
        'sale_purchase',
        'web_studio',
        'website_appointment',
        'website_crm',
        'website_sale_stock',
        'theme_anelusia',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/knowledge_attachments.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/stock_function.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/mrp_bom.xml',
        'data/mrp_bom_line.xml',
        'data/pos_config.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_member.xml',
        'data/appointment_type.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_quant.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/purchase_order_confirm.xml',
        'demo/stock_picking_validation.xml',
        'demo/website_attachments.xml',
        'demo/website_view.xml',
        'demo/website.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
