# -*- coding: utf-8 -*-
{
    'name': 'Pharmaceuticals Retailers',
    'version': '1.0',
    'category': 'Retail',
    'description': """
This setup is for pharmacy retail companies that purchase and sell products.
They maintain the stock lot wise and also manage the expiry of the lots.
""",
    'author': 'Odoo S.A',
    'depends': [
        'account_check_printing',
        'account_followup',
        'calendar',
        'contacts',
        'knowledge',
        'partner_autocomplete',
        'pos_sale',
        'product_expiry',
        'project_enterprise',
        'project_sms',
        'purchase_stock',
        'sale_loyalty',
        'sale_margin',
        'sale_planning',
        'sale_product_configurator',
        'sale_project',
        'sale_purchase',
        'sale_stock',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/account_analytic_plan.xml',
        'data/uom_category.xml',
        'data/uom_uom.xml',
        'data/res_partner.xml',
        'data/product_template.xml',
        'data/project_project_stage.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_pricelist.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/loyalty_program.xml',
        'data/loyalty_reward.xml',
        'data/loyalty_rule.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_member.xml',
        'data/res_config_settings.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/stock_lot.xml',
        'demo/product_supplierinfo.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_post.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_loyalty_reward_wizard.xml',
        'demo/sale_order_post.xml',
        'demo/project_task.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
