{
    'name': 'Escape Rooms',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'base_industry_data',
        'knowledge',
        'pos_loyalty',
        'sale_crm',
        'sale_planning',
        'website_appointment',
        'website_crm',
        'website_sale_loyalty',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/appointment_type.xml',
        'data/appointment_resource.xml',
        'data/crm_tag.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/pos_category.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/product_product.xml',
        'demo/loyalty_program.xml',
        'demo/loyalty_rule.xml',
        'demo/website_view.xml',
        'demo/crm_lead.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/planning_slot.xml',
        'demo/loyalty_reward.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'data/website_view.xml',
        'demo/website_view.xml',
    ],
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=escape_rooms",
    'website': "https://www.odoo.com/all-industries",
}
