{
    'name': 'Real Estate Agency',
    'version': '1.0',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'base_automation',
        'crm_enterprise',
        'hr',
        'knowledge',
        'project_enterprise',
        'sale_commission',
        'sale_commission_linked_achievement',
        'sale_crm',
        'sale_project',
        'sign',
        'web_studio',
        'website_crm',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/ir_model_fields.xml',
        'data/crm_team.xml',
        'data/mail_template.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_item_type.xml',
        'data/sign_item.xml',
        'data/res_partner_category.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/sale_commission_plan.xml',
        'data/sale_commission_plan_achievement.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/crm_stage.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_ribbon.xml',
        'data/product_template.xml',
        'data/ir_attachment_post.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
        'data/crm_tag.xml',
        'data/website_view.xml',
        'data/website_page.xml',
        'data/website_menu.xml',
        'data/website_theme_apply.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/res_users.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_template.xml',
        'demo/product_image.xml',
        'demo/product_template_attribute_line.xml',
        'demo/product_template_attribute_value.xml',
        'demo/product_product.xml',
        'demo/x_product_template_line.xml',
        'demo/create_link.xml',
        'demo/calendar_event.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/res_partner_category.xml',
        'demo/sale_commission_plan_user.xml',
        'demo/ir_attachment_post.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_theme_apply.xml',
        'demo/website.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'real_estate/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/website_view.xml",
        "static/src/js/my_tour.js",
        "demo/website_view.xml",
    ],
    'images': ['images/main.png'],
    'license': 'OPL-1',
}
