{
    'name': 'Handyman Services',
    'version': '1.0',
    'category': 'Studio',
    'description': "",
    'depends': [
        'account_edi_ubl_cii',
        'account_invoice_extract',
        'account_online_synchronization',
        'appointment_account_payment',
        'base_vat',
        'category_customizations_studio',
        'crm_enterprise',
        'crm_iap_enrich',
        'crm_iap_mine',
        'hr_expense',
        'hr_skills',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'partner_autocomplete',
        'product_barcodelookup',
        'project_purchase',
        'project_sms',
        'project_timesheet_forecast_sale',
        'sale_async_emails',
        'sale_crm',
        'sale_pdf_quote_builder',
        'sale_purchase_stock',
        'snailmail_account',
        'spreadsheet_sale_management',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/crm_stage.xml',
        'data/ir_module_module.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/worksheet_template.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/uom_category.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/project_project_stage.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/account_analytic_plan.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_team.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/planning_recurrency.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/product_supplierinfo.xml',
        'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/project_project.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'author': 'Odoo S.A.',
    'images': ['images/main.png'],
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
}
