{
    'name': 'Handyman Services',
    'version': '1.0',
    'category': 'Services',
    'description': "",
    'depends': [
        'account_online_synchronization',
        'appointment_account_payment',
        'crm_enterprise',
        'hr_skills',
        'industry_fsm_sale_report',
        'industry_fsm_stock',
        'knowledge',
        'product_barcodelookup',
        'project_purchase',
        'project_sms',
        'project_timesheet_forecast_sale',
        'sale_crm',
        'sale_pdf_quote_builder',
        'sale_purchase_stock',
        'spreadsheet_sale_management',
        'web_studio',
    ],
    'data': [
        'data/res_config_setting.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_actions_server.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/planning_role.xml',
        'data/product_pricelist.xml',
        'data/worksheet_template.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/account_analytic_account.xml',
        'demo/crm_lead.xml',
        'demo/hr_employee.xml',
        'demo/planning_recurrency.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/planning_slot_template.xml',
        'demo/planning_slot.xml',
        'demo/product_supplierinfo.xml',
        # 'demo/project_task.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/project_project.xml',
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'handyman/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
    ],
    'images': ['images/main.png'],
}
