{
    'name': 'Spa Resort',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_hr',
        'base_industry_data',
        'contacts',
        'knowledge',
        'pos_loyalty',
        'sale_planning',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/product_product.xml',
        'data/appointment_resource.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/pos_config.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_product.xml',
        'demo/appointment_type.xml',
        'demo/loyalty_program.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/website_view.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/pos_order.xml',
        'demo/loyalty_reward.xml',
        'demo/pos_order_line.xml',
        'demo/loyalty_rule.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/account_move.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/loyalty_generate_wizard.xml',
        'demo/sale_loyalty_wizard.xml',
        'demo/sale_order_confirm.xml',
        'demo/pos_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
